// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface AtivoB3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.AtivoB3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticker = 1;</code>
   * @return The ticker.
   */
  java.lang.String getTicker();
  /**
   * <code>string ticker = 1;</code>
   * @return The bytes for ticker.
   */
  com.google.protobuf.ByteString
      getTickerBytes();

  /**
   * <code>double precoAtual = 2;</code>
   * @return The precoAtual.
   */
  double getPrecoAtual();

  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  java.lang.String getDescricao();
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  com.google.protobuf.ByteString
      getDescricaoBytes();

  /**
   * <pre>
   * Ibovespa, SmallCaps
   * </pre>
   *
   * <code>string segmento = 4;</code>
   * @return The segmento.
   */
  java.lang.String getSegmento();
  /**
   * <pre>
   * Ibovespa, SmallCaps
   * </pre>
   *
   * <code>string segmento = 4;</code>
   * @return The bytes for segmento.
   */
  com.google.protobuf.ByteString
      getSegmentoBytes();

  /**
   * <code>int64 volumeNegociado = 5;</code>
   * @return The volumeNegociado.
   */
  long getVolumeNegociado();
}
