// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Ativo}
 */
@com.google.protobuf.Generated
public final class Ativo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.Ativo)
    AtivoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Ativo");
  }
  // Use Ativo.newBuilder() to construct.
  private Ativo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Ativo() {
    ticker_ = "";
    descricao_ = "";
    tipo_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.Ativo.class, br.ufc.ds.trabalho2.protobuf.Ativo.Builder.class);
  }

  private int tipoSpecificoCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object tipoSpecifico_;
  public enum TipoSpecificoCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ATIVOB3(5),
    ATIVOFIXO(6),
    TIPOSPECIFICO_NOT_SET(0);
    private final int value;
    private TipoSpecificoCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipoSpecificoCase valueOf(int value) {
      return forNumber(value);
    }

    public static TipoSpecificoCase forNumber(int value) {
      switch (value) {
        case 5: return ATIVOB3;
        case 6: return ATIVOFIXO;
        case 0: return TIPOSPECIFICO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TipoSpecificoCase
  getTipoSpecificoCase() {
    return TipoSpecificoCase.forNumber(
        tipoSpecificoCase_);
  }

  public static final int TICKER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ticker_ = "";
  /**
   * <code>string ticker = 1;</code>
   * @return The ticker.
   */
  @java.lang.Override
  public java.lang.String getTicker() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ticker_ = s;
      return s;
    }
  }
  /**
   * <code>string ticker = 1;</code>
   * @return The bytes for ticker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTickerBytes() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRECOATUAL_FIELD_NUMBER = 2;
  private double precoAtual_ = 0D;
  /**
   * <code>double precoAtual = 2;</code>
   * @return The precoAtual.
   */
  @java.lang.Override
  public double getPrecoAtual() {
    return precoAtual_;
  }

  public static final int DESCRICAO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object descricao_ = "";
  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  @java.lang.Override
  public java.lang.String getDescricao() {
    java.lang.Object ref = descricao_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descricao_ = s;
      return s;
    }
  }
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescricaoBytes() {
    java.lang.Object ref = descricao_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descricao_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIPO_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tipo_ = "";
  /**
   * <pre>
   * "ACAO_B3" ou "RENDA_FIXA"
   * </pre>
   *
   * <code>string tipo = 4;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public java.lang.String getTipo() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "ACAO_B3" ou "RENDA_FIXA"
   * </pre>
   *
   * <code>string tipo = 4;</code>
   * @return The bytes for tipo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipoBytes() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATIVOB3_FIELD_NUMBER = 5;
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
   * @return Whether the ativoB3 field is set.
   */
  @java.lang.Override
  public boolean hasAtivoB3() {
    return tipoSpecificoCase_ == 5;
  }
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
   * @return The ativoB3.
   */
  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.AtivoB3 getAtivoB3() {
    if (tipoSpecificoCase_ == 5) {
       return (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_;
    }
    return br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance();
  }
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
   */
  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.AtivoB3OrBuilder getAtivoB3OrBuilder() {
    if (tipoSpecificoCase_ == 5) {
       return (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_;
    }
    return br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance();
  }

  public static final int ATIVOFIXO_FIELD_NUMBER = 6;
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
   * @return Whether the ativoFixo field is set.
   */
  @java.lang.Override
  public boolean hasAtivoFixo() {
    return tipoSpecificoCase_ == 6;
  }
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
   * @return The ativoFixo.
   */
  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.AtivoFixo getAtivoFixo() {
    if (tipoSpecificoCase_ == 6) {
       return (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_;
    }
    return br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
  }
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
   */
  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder getAtivoFixoOrBuilder() {
    if (tipoSpecificoCase_ == 6) {
       return (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_;
    }
    return br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ticker_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ticker_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoAtual_) != 0) {
      output.writeDouble(2, precoAtual_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(descricao_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, descricao_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, tipo_);
    }
    if (tipoSpecificoCase_ == 5) {
      output.writeMessage(5, (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_);
    }
    if (tipoSpecificoCase_ == 6) {
      output.writeMessage(6, (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ticker_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ticker_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoAtual_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, precoAtual_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(descricao_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, descricao_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, tipo_);
    }
    if (tipoSpecificoCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_);
    }
    if (tipoSpecificoCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.Ativo)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.Ativo other = (br.ufc.ds.trabalho2.protobuf.Ativo) obj;

    if (!getTicker()
        .equals(other.getTicker())) return false;
    if (java.lang.Double.doubleToLongBits(getPrecoAtual())
        != java.lang.Double.doubleToLongBits(
            other.getPrecoAtual())) return false;
    if (!getDescricao()
        .equals(other.getDescricao())) return false;
    if (!getTipo()
        .equals(other.getTipo())) return false;
    if (!getTipoSpecificoCase().equals(other.getTipoSpecificoCase())) return false;
    switch (tipoSpecificoCase_) {
      case 5:
        if (!getAtivoB3()
            .equals(other.getAtivoB3())) return false;
        break;
      case 6:
        if (!getAtivoFixo()
            .equals(other.getAtivoFixo())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TICKER_FIELD_NUMBER;
    hash = (53 * hash) + getTicker().hashCode();
    hash = (37 * hash) + PRECOATUAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrecoAtual()));
    hash = (37 * hash) + DESCRICAO_FIELD_NUMBER;
    hash = (53 * hash) + getDescricao().hashCode();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo().hashCode();
    switch (tipoSpecificoCase_) {
      case 5:
        hash = (37 * hash) + ATIVOB3_FIELD_NUMBER;
        hash = (53 * hash) + getAtivoB3().hashCode();
        break;
      case 6:
        hash = (37 * hash) + ATIVOFIXO_FIELD_NUMBER;
        hash = (53 * hash) + getAtivoFixo().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.Ativo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.Ativo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Ativo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.Ativo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Ativo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.Ativo)
      br.ufc.ds.trabalho2.protobuf.AtivoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.Ativo.class, br.ufc.ds.trabalho2.protobuf.Ativo.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.Ativo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ticker_ = "";
      precoAtual_ = 0D;
      descricao_ = "";
      tipo_ = "";
      if (ativoB3Builder_ != null) {
        ativoB3Builder_.clear();
      }
      if (ativoFixoBuilder_ != null) {
        ativoFixoBuilder_.clear();
      }
      tipoSpecificoCase_ = 0;
      tipoSpecifico_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Ativo getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.Ativo.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Ativo build() {
      br.ufc.ds.trabalho2.protobuf.Ativo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Ativo buildPartial() {
      br.ufc.ds.trabalho2.protobuf.Ativo result = new br.ufc.ds.trabalho2.protobuf.Ativo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.Ativo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ticker_ = ticker_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.precoAtual_ = precoAtual_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.descricao_ = descricao_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tipo_ = tipo_;
      }
    }

    private void buildPartialOneofs(br.ufc.ds.trabalho2.protobuf.Ativo result) {
      result.tipoSpecificoCase_ = tipoSpecificoCase_;
      result.tipoSpecifico_ = this.tipoSpecifico_;
      if (tipoSpecificoCase_ == 5 &&
          ativoB3Builder_ != null) {
        result.tipoSpecifico_ = ativoB3Builder_.build();
      }
      if (tipoSpecificoCase_ == 6 &&
          ativoFixoBuilder_ != null) {
        result.tipoSpecifico_ = ativoFixoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.Ativo) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.Ativo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.Ativo other) {
      if (other == br.ufc.ds.trabalho2.protobuf.Ativo.getDefaultInstance()) return this;
      if (!other.getTicker().isEmpty()) {
        ticker_ = other.ticker_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPrecoAtual()) != 0) {
        setPrecoAtual(other.getPrecoAtual());
      }
      if (!other.getDescricao().isEmpty()) {
        descricao_ = other.descricao_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTipo().isEmpty()) {
        tipo_ = other.tipo_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      switch (other.getTipoSpecificoCase()) {
        case ATIVOB3: {
          mergeAtivoB3(other.getAtivoB3());
          break;
        }
        case ATIVOFIXO: {
          mergeAtivoFixo(other.getAtivoFixo());
          break;
        }
        case TIPOSPECIFICO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ticker_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              precoAtual_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              descricao_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              tipo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetAtivoB3FieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoSpecificoCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetAtivoFixoFieldBuilder().getBuilder(),
                  extensionRegistry);
              tipoSpecificoCase_ = 6;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int tipoSpecificoCase_ = 0;
    private java.lang.Object tipoSpecifico_;
    public TipoSpecificoCase
        getTipoSpecificoCase() {
      return TipoSpecificoCase.forNumber(
          tipoSpecificoCase_);
    }

    public Builder clearTipoSpecifico() {
      tipoSpecificoCase_ = 0;
      tipoSpecifico_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object ticker_ = "";
    /**
     * <code>string ticker = 1;</code>
     * @return The ticker.
     */
    public java.lang.String getTicker() {
      java.lang.Object ref = ticker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ticker = 1;</code>
     * @return The bytes for ticker.
     */
    public com.google.protobuf.ByteString
        getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ticker = 1;</code>
     * @param value The ticker to set.
     * @return This builder for chaining.
     */
    public Builder setTicker(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ticker_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ticker = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTicker() {
      ticker_ = getDefaultInstance().getTicker();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ticker = 1;</code>
     * @param value The bytes for ticker to set.
     * @return This builder for chaining.
     */
    public Builder setTickerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ticker_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double precoAtual_ ;
    /**
     * <code>double precoAtual = 2;</code>
     * @return The precoAtual.
     */
    @java.lang.Override
    public double getPrecoAtual() {
      return precoAtual_;
    }
    /**
     * <code>double precoAtual = 2;</code>
     * @param value The precoAtual to set.
     * @return This builder for chaining.
     */
    public Builder setPrecoAtual(double value) {

      precoAtual_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double precoAtual = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecoAtual() {
      bitField0_ = (bitField0_ & ~0x00000002);
      precoAtual_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object descricao_ = "";
    /**
     * <code>string descricao = 3;</code>
     * @return The descricao.
     */
    public java.lang.String getDescricao() {
      java.lang.Object ref = descricao_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descricao_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string descricao = 3;</code>
     * @return The bytes for descricao.
     */
    public com.google.protobuf.ByteString
        getDescricaoBytes() {
      java.lang.Object ref = descricao_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descricao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string descricao = 3;</code>
     * @param value The descricao to set.
     * @return This builder for chaining.
     */
    public Builder setDescricao(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      descricao_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string descricao = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescricao() {
      descricao_ = getDefaultInstance().getDescricao();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string descricao = 3;</code>
     * @param value The bytes for descricao to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      descricao_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object tipo_ = "";
    /**
     * <pre>
     * "ACAO_B3" ou "RENDA_FIXA"
     * </pre>
     *
     * <code>string tipo = 4;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "ACAO_B3" ou "RENDA_FIXA"
     * </pre>
     *
     * <code>string tipo = 4;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "ACAO_B3" ou "RENDA_FIXA"
     * </pre>
     *
     * <code>string tipo = 4;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tipo_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ACAO_B3" ou "RENDA_FIXA"
     * </pre>
     *
     * <code>string tipo = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      tipo_ = getDefaultInstance().getTipo();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ACAO_B3" ou "RENDA_FIXA"
     * </pre>
     *
     * <code>string tipo = 4;</code>
     * @param value The bytes for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tipo_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        br.ufc.ds.trabalho2.protobuf.AtivoB3, br.ufc.ds.trabalho2.protobuf.AtivoB3.Builder, br.ufc.ds.trabalho2.protobuf.AtivoB3OrBuilder> ativoB3Builder_;
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     * @return Whether the ativoB3 field is set.
     */
    @java.lang.Override
    public boolean hasAtivoB3() {
      return tipoSpecificoCase_ == 5;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     * @return The ativoB3.
     */
    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoB3 getAtivoB3() {
      if (ativoB3Builder_ == null) {
        if (tipoSpecificoCase_ == 5) {
          return (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_;
        }
        return br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance();
      } else {
        if (tipoSpecificoCase_ == 5) {
          return ativoB3Builder_.getMessage();
        }
        return br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance();
      }
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    public Builder setAtivoB3(br.ufc.ds.trabalho2.protobuf.AtivoB3 value) {
      if (ativoB3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoSpecifico_ = value;
        onChanged();
      } else {
        ativoB3Builder_.setMessage(value);
      }
      tipoSpecificoCase_ = 5;
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    public Builder setAtivoB3(
        br.ufc.ds.trabalho2.protobuf.AtivoB3.Builder builderForValue) {
      if (ativoB3Builder_ == null) {
        tipoSpecifico_ = builderForValue.build();
        onChanged();
      } else {
        ativoB3Builder_.setMessage(builderForValue.build());
      }
      tipoSpecificoCase_ = 5;
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    public Builder mergeAtivoB3(br.ufc.ds.trabalho2.protobuf.AtivoB3 value) {
      if (ativoB3Builder_ == null) {
        if (tipoSpecificoCase_ == 5 &&
            tipoSpecifico_ != br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance()) {
          tipoSpecifico_ = br.ufc.ds.trabalho2.protobuf.AtivoB3.newBuilder((br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoSpecifico_ = value;
        }
        onChanged();
      } else {
        if (tipoSpecificoCase_ == 5) {
          ativoB3Builder_.mergeFrom(value);
        } else {
          ativoB3Builder_.setMessage(value);
        }
      }
      tipoSpecificoCase_ = 5;
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    public Builder clearAtivoB3() {
      if (ativoB3Builder_ == null) {
        if (tipoSpecificoCase_ == 5) {
          tipoSpecificoCase_ = 0;
          tipoSpecifico_ = null;
          onChanged();
        }
      } else {
        if (tipoSpecificoCase_ == 5) {
          tipoSpecificoCase_ = 0;
          tipoSpecifico_ = null;
        }
        ativoB3Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    public br.ufc.ds.trabalho2.protobuf.AtivoB3.Builder getAtivoB3Builder() {
      return internalGetAtivoB3FieldBuilder().getBuilder();
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoB3OrBuilder getAtivoB3OrBuilder() {
      if ((tipoSpecificoCase_ == 5) && (ativoB3Builder_ != null)) {
        return ativoB3Builder_.getMessageOrBuilder();
      } else {
        if (tipoSpecificoCase_ == 5) {
          return (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_;
        }
        return br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance();
      }
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        br.ufc.ds.trabalho2.protobuf.AtivoB3, br.ufc.ds.trabalho2.protobuf.AtivoB3.Builder, br.ufc.ds.trabalho2.protobuf.AtivoB3OrBuilder> 
        internalGetAtivoB3FieldBuilder() {
      if (ativoB3Builder_ == null) {
        if (!(tipoSpecificoCase_ == 5)) {
          tipoSpecifico_ = br.ufc.ds.trabalho2.protobuf.AtivoB3.getDefaultInstance();
        }
        ativoB3Builder_ = new com.google.protobuf.SingleFieldBuilder<
            br.ufc.ds.trabalho2.protobuf.AtivoB3, br.ufc.ds.trabalho2.protobuf.AtivoB3.Builder, br.ufc.ds.trabalho2.protobuf.AtivoB3OrBuilder>(
                (br.ufc.ds.trabalho2.protobuf.AtivoB3) tipoSpecifico_,
                getParentForChildren(),
                isClean());
        tipoSpecifico_ = null;
      }
      tipoSpecificoCase_ = 5;
      onChanged();
      return ativoB3Builder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        br.ufc.ds.trabalho2.protobuf.AtivoFixo, br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder, br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder> ativoFixoBuilder_;
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     * @return Whether the ativoFixo field is set.
     */
    @java.lang.Override
    public boolean hasAtivoFixo() {
      return tipoSpecificoCase_ == 6;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     * @return The ativoFixo.
     */
    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoFixo getAtivoFixo() {
      if (ativoFixoBuilder_ == null) {
        if (tipoSpecificoCase_ == 6) {
          return (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_;
        }
        return br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
      } else {
        if (tipoSpecificoCase_ == 6) {
          return ativoFixoBuilder_.getMessage();
        }
        return br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
      }
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    public Builder setAtivoFixo(br.ufc.ds.trabalho2.protobuf.AtivoFixo value) {
      if (ativoFixoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tipoSpecifico_ = value;
        onChanged();
      } else {
        ativoFixoBuilder_.setMessage(value);
      }
      tipoSpecificoCase_ = 6;
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    public Builder setAtivoFixo(
        br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder builderForValue) {
      if (ativoFixoBuilder_ == null) {
        tipoSpecifico_ = builderForValue.build();
        onChanged();
      } else {
        ativoFixoBuilder_.setMessage(builderForValue.build());
      }
      tipoSpecificoCase_ = 6;
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    public Builder mergeAtivoFixo(br.ufc.ds.trabalho2.protobuf.AtivoFixo value) {
      if (ativoFixoBuilder_ == null) {
        if (tipoSpecificoCase_ == 6 &&
            tipoSpecifico_ != br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance()) {
          tipoSpecifico_ = br.ufc.ds.trabalho2.protobuf.AtivoFixo.newBuilder((br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_)
              .mergeFrom(value).buildPartial();
        } else {
          tipoSpecifico_ = value;
        }
        onChanged();
      } else {
        if (tipoSpecificoCase_ == 6) {
          ativoFixoBuilder_.mergeFrom(value);
        } else {
          ativoFixoBuilder_.setMessage(value);
        }
      }
      tipoSpecificoCase_ = 6;
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    public Builder clearAtivoFixo() {
      if (ativoFixoBuilder_ == null) {
        if (tipoSpecificoCase_ == 6) {
          tipoSpecificoCase_ = 0;
          tipoSpecifico_ = null;
          onChanged();
        }
      } else {
        if (tipoSpecificoCase_ == 6) {
          tipoSpecificoCase_ = 0;
          tipoSpecifico_ = null;
        }
        ativoFixoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    public br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder getAtivoFixoBuilder() {
      return internalGetAtivoFixoFieldBuilder().getBuilder();
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder getAtivoFixoOrBuilder() {
      if ((tipoSpecificoCase_ == 6) && (ativoFixoBuilder_ != null)) {
        return ativoFixoBuilder_.getMessageOrBuilder();
      } else {
        if (tipoSpecificoCase_ == 6) {
          return (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_;
        }
        return br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
      }
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        br.ufc.ds.trabalho2.protobuf.AtivoFixo, br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder, br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder> 
        internalGetAtivoFixoFieldBuilder() {
      if (ativoFixoBuilder_ == null) {
        if (!(tipoSpecificoCase_ == 6)) {
          tipoSpecifico_ = br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
        }
        ativoFixoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            br.ufc.ds.trabalho2.protobuf.AtivoFixo, br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder, br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder>(
                (br.ufc.ds.trabalho2.protobuf.AtivoFixo) tipoSpecifico_,
                getParentForChildren(),
                isClean());
        tipoSpecifico_ = null;
      }
      tipoSpecificoCase_ = 6;
      onChanged();
      return ativoFixoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.Ativo)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.Ativo)
  private static final br.ufc.ds.trabalho2.protobuf.Ativo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.Ativo();
  }

  public static br.ufc.ds.trabalho2.protobuf.Ativo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ativo>
      PARSER = new com.google.protobuf.AbstractParser<Ativo>() {
    @java.lang.Override
    public Ativo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ativo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ativo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.Ativo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

