// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface AtivoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.Ativo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticker = 1;</code>
   * @return The ticker.
   */
  java.lang.String getTicker();
  /**
   * <code>string ticker = 1;</code>
   * @return The bytes for ticker.
   */
  com.google.protobuf.ByteString
      getTickerBytes();

  /**
   * <code>double precoAtual = 2;</code>
   * @return The precoAtual.
   */
  double getPrecoAtual();

  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  java.lang.String getDescricao();
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  com.google.protobuf.ByteString
      getDescricaoBytes();

  /**
   * <pre>
   * "ACAO_B3" ou "RENDA_FIXA"
   * </pre>
   *
   * <code>string tipo = 4;</code>
   * @return The tipo.
   */
  java.lang.String getTipo();
  /**
   * <pre>
   * "ACAO_B3" ou "RENDA_FIXA"
   * </pre>
   *
   * <code>string tipo = 4;</code>
   * @return The bytes for tipo.
   */
  com.google.protobuf.ByteString
      getTipoBytes();

  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
   * @return Whether the ativoB3 field is set.
   */
  boolean hasAtivoB3();
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
   * @return The ativoB3.
   */
  br.ufc.ds.trabalho2.protobuf.AtivoB3 getAtivoB3();
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoB3 ativoB3 = 5;</code>
   */
  br.ufc.ds.trabalho2.protobuf.AtivoB3OrBuilder getAtivoB3OrBuilder();

  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
   * @return Whether the ativoFixo field is set.
   */
  boolean hasAtivoFixo();
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
   * @return The ativoFixo.
   */
  br.ufc.ds.trabalho2.protobuf.AtivoFixo getAtivoFixo();
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.AtivoFixo ativoFixo = 6;</code>
   */
  br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder getAtivoFixoOrBuilder();

  br.ufc.ds.trabalho2.protobuf.Ativo.TipoSpecificoCase getTipoSpecificoCase();
}
