// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.AtivoFixo}
 */
@com.google.protobuf.Generated
public final class AtivoFixo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.AtivoFixo)
    AtivoFixoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "AtivoFixo");
  }
  // Use AtivoFixo.newBuilder() to construct.
  private AtivoFixo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AtivoFixo() {
    ticker_ = "";
    descricao_ = "";
    dataVencimento_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.AtivoFixo.class, br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder.class);
  }

  public static final int TICKER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ticker_ = "";
  /**
   * <code>string ticker = 1;</code>
   * @return The ticker.
   */
  @java.lang.Override
  public java.lang.String getTicker() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ticker_ = s;
      return s;
    }
  }
  /**
   * <code>string ticker = 1;</code>
   * @return The bytes for ticker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTickerBytes() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRECOATUAL_FIELD_NUMBER = 2;
  private double precoAtual_ = 0D;
  /**
   * <code>double precoAtual = 2;</code>
   * @return The precoAtual.
   */
  @java.lang.Override
  public double getPrecoAtual() {
    return precoAtual_;
  }

  public static final int DESCRICAO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object descricao_ = "";
  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  @java.lang.Override
  public java.lang.String getDescricao() {
    java.lang.Object ref = descricao_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descricao_ = s;
      return s;
    }
  }
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescricaoBytes() {
    java.lang.Object ref = descricao_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descricao_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAXAJUROS_FIELD_NUMBER = 4;
  private double taxaJuros_ = 0D;
  /**
   * <code>double taxaJuros = 4;</code>
   * @return The taxaJuros.
   */
  @java.lang.Override
  public double getTaxaJuros() {
    return taxaJuros_;
  }

  public static final int DATAVENCIMENTO_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataVencimento_ = "";
  /**
   * <code>string dataVencimento = 5;</code>
   * @return The dataVencimento.
   */
  @java.lang.Override
  public java.lang.String getDataVencimento() {
    java.lang.Object ref = dataVencimento_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataVencimento_ = s;
      return s;
    }
  }
  /**
   * <code>string dataVencimento = 5;</code>
   * @return The bytes for dataVencimento.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataVencimentoBytes() {
    java.lang.Object ref = dataVencimento_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataVencimento_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ticker_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ticker_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoAtual_) != 0) {
      output.writeDouble(2, precoAtual_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(descricao_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, descricao_);
    }
    if (java.lang.Double.doubleToRawLongBits(taxaJuros_) != 0) {
      output.writeDouble(4, taxaJuros_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataVencimento_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, dataVencimento_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ticker_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ticker_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoAtual_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, precoAtual_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(descricao_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, descricao_);
    }
    if (java.lang.Double.doubleToRawLongBits(taxaJuros_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, taxaJuros_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataVencimento_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, dataVencimento_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.AtivoFixo)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.AtivoFixo other = (br.ufc.ds.trabalho2.protobuf.AtivoFixo) obj;

    if (!getTicker()
        .equals(other.getTicker())) return false;
    if (java.lang.Double.doubleToLongBits(getPrecoAtual())
        != java.lang.Double.doubleToLongBits(
            other.getPrecoAtual())) return false;
    if (!getDescricao()
        .equals(other.getDescricao())) return false;
    if (java.lang.Double.doubleToLongBits(getTaxaJuros())
        != java.lang.Double.doubleToLongBits(
            other.getTaxaJuros())) return false;
    if (!getDataVencimento()
        .equals(other.getDataVencimento())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TICKER_FIELD_NUMBER;
    hash = (53 * hash) + getTicker().hashCode();
    hash = (37 * hash) + PRECOATUAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrecoAtual()));
    hash = (37 * hash) + DESCRICAO_FIELD_NUMBER;
    hash = (53 * hash) + getDescricao().hashCode();
    hash = (37 * hash) + TAXAJUROS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTaxaJuros()));
    hash = (37 * hash) + DATAVENCIMENTO_FIELD_NUMBER;
    hash = (53 * hash) + getDataVencimento().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.AtivoFixo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.AtivoFixo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.AtivoFixo)
      br.ufc.ds.trabalho2.protobuf.AtivoFixoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.AtivoFixo.class, br.ufc.ds.trabalho2.protobuf.AtivoFixo.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.AtivoFixo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ticker_ = "";
      precoAtual_ = 0D;
      descricao_ = "";
      taxaJuros_ = 0D;
      dataVencimento_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoFixo getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoFixo build() {
      br.ufc.ds.trabalho2.protobuf.AtivoFixo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.AtivoFixo buildPartial() {
      br.ufc.ds.trabalho2.protobuf.AtivoFixo result = new br.ufc.ds.trabalho2.protobuf.AtivoFixo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.AtivoFixo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ticker_ = ticker_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.precoAtual_ = precoAtual_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.descricao_ = descricao_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.taxaJuros_ = taxaJuros_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dataVencimento_ = dataVencimento_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.AtivoFixo) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.AtivoFixo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.AtivoFixo other) {
      if (other == br.ufc.ds.trabalho2.protobuf.AtivoFixo.getDefaultInstance()) return this;
      if (!other.getTicker().isEmpty()) {
        ticker_ = other.ticker_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPrecoAtual()) != 0) {
        setPrecoAtual(other.getPrecoAtual());
      }
      if (!other.getDescricao().isEmpty()) {
        descricao_ = other.descricao_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getTaxaJuros()) != 0) {
        setTaxaJuros(other.getTaxaJuros());
      }
      if (!other.getDataVencimento().isEmpty()) {
        dataVencimento_ = other.dataVencimento_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ticker_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              precoAtual_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              descricao_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 33: {
              taxaJuros_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 42: {
              dataVencimento_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ticker_ = "";
    /**
     * <code>string ticker = 1;</code>
     * @return The ticker.
     */
    public java.lang.String getTicker() {
      java.lang.Object ref = ticker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ticker = 1;</code>
     * @return The bytes for ticker.
     */
    public com.google.protobuf.ByteString
        getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ticker = 1;</code>
     * @param value The ticker to set.
     * @return This builder for chaining.
     */
    public Builder setTicker(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ticker_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ticker = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTicker() {
      ticker_ = getDefaultInstance().getTicker();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ticker = 1;</code>
     * @param value The bytes for ticker to set.
     * @return This builder for chaining.
     */
    public Builder setTickerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ticker_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double precoAtual_ ;
    /**
     * <code>double precoAtual = 2;</code>
     * @return The precoAtual.
     */
    @java.lang.Override
    public double getPrecoAtual() {
      return precoAtual_;
    }
    /**
     * <code>double precoAtual = 2;</code>
     * @param value The precoAtual to set.
     * @return This builder for chaining.
     */
    public Builder setPrecoAtual(double value) {

      precoAtual_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double precoAtual = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecoAtual() {
      bitField0_ = (bitField0_ & ~0x00000002);
      precoAtual_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object descricao_ = "";
    /**
     * <code>string descricao = 3;</code>
     * @return The descricao.
     */
    public java.lang.String getDescricao() {
      java.lang.Object ref = descricao_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descricao_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string descricao = 3;</code>
     * @return The bytes for descricao.
     */
    public com.google.protobuf.ByteString
        getDescricaoBytes() {
      java.lang.Object ref = descricao_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descricao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string descricao = 3;</code>
     * @param value The descricao to set.
     * @return This builder for chaining.
     */
    public Builder setDescricao(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      descricao_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string descricao = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescricao() {
      descricao_ = getDefaultInstance().getDescricao();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string descricao = 3;</code>
     * @param value The bytes for descricao to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      descricao_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private double taxaJuros_ ;
    /**
     * <code>double taxaJuros = 4;</code>
     * @return The taxaJuros.
     */
    @java.lang.Override
    public double getTaxaJuros() {
      return taxaJuros_;
    }
    /**
     * <code>double taxaJuros = 4;</code>
     * @param value The taxaJuros to set.
     * @return This builder for chaining.
     */
    public Builder setTaxaJuros(double value) {

      taxaJuros_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double taxaJuros = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaxaJuros() {
      bitField0_ = (bitField0_ & ~0x00000008);
      taxaJuros_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object dataVencimento_ = "";
    /**
     * <code>string dataVencimento = 5;</code>
     * @return The dataVencimento.
     */
    public java.lang.String getDataVencimento() {
      java.lang.Object ref = dataVencimento_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataVencimento_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataVencimento = 5;</code>
     * @return The bytes for dataVencimento.
     */
    public com.google.protobuf.ByteString
        getDataVencimentoBytes() {
      java.lang.Object ref = dataVencimento_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataVencimento_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataVencimento = 5;</code>
     * @param value The dataVencimento to set.
     * @return This builder for chaining.
     */
    public Builder setDataVencimento(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataVencimento_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string dataVencimento = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataVencimento() {
      dataVencimento_ = getDefaultInstance().getDataVencimento();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string dataVencimento = 5;</code>
     * @param value The bytes for dataVencimento to set.
     * @return This builder for chaining.
     */
    public Builder setDataVencimentoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataVencimento_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.AtivoFixo)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.AtivoFixo)
  private static final br.ufc.ds.trabalho2.protobuf.AtivoFixo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.AtivoFixo();
  }

  public static br.ufc.ds.trabalho2.protobuf.AtivoFixo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AtivoFixo>
      PARSER = new com.google.protobuf.AbstractParser<AtivoFixo>() {
    @java.lang.Override
    public AtivoFixo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AtivoFixo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AtivoFixo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.AtivoFixo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

