// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface AtivoFixoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.AtivoFixo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticker = 1;</code>
   * @return The ticker.
   */
  java.lang.String getTicker();
  /**
   * <code>string ticker = 1;</code>
   * @return The bytes for ticker.
   */
  com.google.protobuf.ByteString
      getTickerBytes();

  /**
   * <code>double precoAtual = 2;</code>
   * @return The precoAtual.
   */
  double getPrecoAtual();

  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  java.lang.String getDescricao();
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  com.google.protobuf.ByteString
      getDescricaoBytes();

  /**
   * <code>double taxaJuros = 4;</code>
   * @return The taxaJuros.
   */
  double getTaxaJuros();

  /**
   * <code>string dataVencimento = 5;</code>
   * @return The dataVencimento.
   */
  java.lang.String getDataVencimento();
  /**
   * <code>string dataVencimento = 5;</code>
   * @return The bytes for dataVencimento.
   */
  com.google.protobuf.ByteString
      getDataVencimentoBytes();
}
