// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Carteira}
 */
@com.google.protobuf.Generated
public final class Carteira extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.Carteira)
    CarteiraOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Carteira");
  }
  // Use Carteira.newBuilder() to construct.
  private Carteira(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Carteira() {
    carteiraId_ = "";
    dataCriacao_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetAtivos();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.Carteira.class, br.ufc.ds.trabalho2.protobuf.Carteira.Builder.class);
  }

  public static final int CARTEIRAID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object carteiraId_ = "";
  /**
   * <code>string carteiraId = 1;</code>
   * @return The carteiraId.
   */
  @java.lang.Override
  public java.lang.String getCarteiraId() {
    java.lang.Object ref = carteiraId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      carteiraId_ = s;
      return s;
    }
  }
  /**
   * <code>string carteiraId = 1;</code>
   * @return The bytes for carteiraId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCarteiraIdBytes() {
    java.lang.Object ref = carteiraId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      carteiraId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATIVOS_FIELD_NUMBER = 2;
  private static final class AtivosDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_AtivosEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> ativos_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetAtivos() {
    if (ativos_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AtivosDefaultEntryHolder.defaultEntry);
    }
    return ativos_;
  }
  public int getAtivosCount() {
    return internalGetAtivos().getMap().size();
  }
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  @java.lang.Override
  public boolean containsAtivos(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetAtivos().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAtivosMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getAtivos() {
    return getAtivosMap();
  }
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getAtivosMap() {
    return internalGetAtivos().getMap();
  }
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  @java.lang.Override
  public long getAtivosOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetAtivos().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  @java.lang.Override
  public long getAtivosOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetAtivos().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SALDODISPONIVEL_FIELD_NUMBER = 3;
  private double saldoDisponivel_ = 0D;
  /**
   * <code>double saldoDisponivel = 3;</code>
   * @return The saldoDisponivel.
   */
  @java.lang.Override
  public double getSaldoDisponivel() {
    return saldoDisponivel_;
  }

  public static final int DATACRIACAO_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataCriacao_ = "";
  /**
   * <code>string dataCriacao = 4;</code>
   * @return The dataCriacao.
   */
  @java.lang.Override
  public java.lang.String getDataCriacao() {
    java.lang.Object ref = dataCriacao_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataCriacao_ = s;
      return s;
    }
  }
  /**
   * <code>string dataCriacao = 4;</code>
   * @return The bytes for dataCriacao.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataCriacaoBytes() {
    java.lang.Object ref = dataCriacao_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataCriacao_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(carteiraId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, carteiraId_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetAtivos(),
        AtivosDefaultEntryHolder.defaultEntry,
        2);
    if (java.lang.Double.doubleToRawLongBits(saldoDisponivel_) != 0) {
      output.writeDouble(3, saldoDisponivel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataCriacao_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, dataCriacao_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(carteiraId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, carteiraId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetAtivos().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      ativos__ = AtivosDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ativos__);
    }
    if (java.lang.Double.doubleToRawLongBits(saldoDisponivel_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, saldoDisponivel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataCriacao_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, dataCriacao_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.Carteira)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.Carteira other = (br.ufc.ds.trabalho2.protobuf.Carteira) obj;

    if (!getCarteiraId()
        .equals(other.getCarteiraId())) return false;
    if (!internalGetAtivos().equals(
        other.internalGetAtivos())) return false;
    if (java.lang.Double.doubleToLongBits(getSaldoDisponivel())
        != java.lang.Double.doubleToLongBits(
            other.getSaldoDisponivel())) return false;
    if (!getDataCriacao()
        .equals(other.getDataCriacao())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARTEIRAID_FIELD_NUMBER;
    hash = (53 * hash) + getCarteiraId().hashCode();
    if (!internalGetAtivos().getMap().isEmpty()) {
      hash = (37 * hash) + ATIVOS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAtivos().hashCode();
    }
    hash = (37 * hash) + SALDODISPONIVEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSaldoDisponivel()));
    hash = (37 * hash) + DATACRIACAO_FIELD_NUMBER;
    hash = (53 * hash) + getDataCriacao().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.Carteira parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.Carteira parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Carteira parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.Carteira prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Carteira}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.Carteira)
      br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetAtivos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableAtivos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.Carteira.class, br.ufc.ds.trabalho2.protobuf.Carteira.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.Carteira.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      carteiraId_ = "";
      internalGetMutableAtivos().clear();
      saldoDisponivel_ = 0D;
      dataCriacao_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Carteira getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Carteira build() {
      br.ufc.ds.trabalho2.protobuf.Carteira result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Carteira buildPartial() {
      br.ufc.ds.trabalho2.protobuf.Carteira result = new br.ufc.ds.trabalho2.protobuf.Carteira(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.Carteira result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.carteiraId_ = carteiraId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ativos_ = internalGetAtivos();
        result.ativos_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.saldoDisponivel_ = saldoDisponivel_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.dataCriacao_ = dataCriacao_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.Carteira) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.Carteira)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.Carteira other) {
      if (other == br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance()) return this;
      if (!other.getCarteiraId().isEmpty()) {
        carteiraId_ = other.carteiraId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableAtivos().mergeFrom(
          other.internalGetAtivos());
      bitField0_ |= 0x00000002;
      if (java.lang.Double.doubleToRawLongBits(other.getSaldoDisponivel()) != 0) {
        setSaldoDisponivel(other.getSaldoDisponivel());
      }
      if (!other.getDataCriacao().isEmpty()) {
        dataCriacao_ = other.dataCriacao_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              carteiraId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              ativos__ = input.readMessage(
                  AtivosDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableAtivos().getMutableMap().put(
                  ativos__.getKey(), ativos__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              saldoDisponivel_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              dataCriacao_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object carteiraId_ = "";
    /**
     * <code>string carteiraId = 1;</code>
     * @return The carteiraId.
     */
    public java.lang.String getCarteiraId() {
      java.lang.Object ref = carteiraId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        carteiraId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string carteiraId = 1;</code>
     * @return The bytes for carteiraId.
     */
    public com.google.protobuf.ByteString
        getCarteiraIdBytes() {
      java.lang.Object ref = carteiraId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carteiraId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string carteiraId = 1;</code>
     * @param value The carteiraId to set.
     * @return This builder for chaining.
     */
    public Builder setCarteiraId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      carteiraId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string carteiraId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCarteiraId() {
      carteiraId_ = getDefaultInstance().getCarteiraId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string carteiraId = 1;</code>
     * @param value The bytes for carteiraId to set.
     * @return This builder for chaining.
     */
    public Builder setCarteiraIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      carteiraId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> ativos_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetAtivos() {
      if (ativos_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AtivosDefaultEntryHolder.defaultEntry);
      }
      return ativos_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableAtivos() {
      if (ativos_ == null) {
        ativos_ = com.google.protobuf.MapField.newMapField(
            AtivosDefaultEntryHolder.defaultEntry);
      }
      if (!ativos_.isMutable()) {
        ativos_ = ativos_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return ativos_;
    }
    public int getAtivosCount() {
      return internalGetAtivos().getMap().size();
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    @java.lang.Override
    public boolean containsAtivos(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAtivos().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAtivosMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getAtivos() {
      return getAtivosMap();
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getAtivosMap() {
      return internalGetAtivos().getMap();
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    @java.lang.Override
    public long getAtivosOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetAtivos().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    @java.lang.Override
    public long getAtivosOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetAtivos().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearAtivos() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableAtivos().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    public Builder removeAtivos(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableAtivos().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableAtivos() {
      bitField0_ |= 0x00000002;
      return internalGetMutableAtivos().getMutableMap();
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    public Builder putAtivos(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableAtivos().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * ticker -&gt; quantidade
     * </pre>
     *
     * <code>map&lt;string, int64&gt; ativos = 2;</code>
     */
    public Builder putAllAtivos(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableAtivos().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }

    private double saldoDisponivel_ ;
    /**
     * <code>double saldoDisponivel = 3;</code>
     * @return The saldoDisponivel.
     */
    @java.lang.Override
    public double getSaldoDisponivel() {
      return saldoDisponivel_;
    }
    /**
     * <code>double saldoDisponivel = 3;</code>
     * @param value The saldoDisponivel to set.
     * @return This builder for chaining.
     */
    public Builder setSaldoDisponivel(double value) {

      saldoDisponivel_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double saldoDisponivel = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaldoDisponivel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      saldoDisponivel_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object dataCriacao_ = "";
    /**
     * <code>string dataCriacao = 4;</code>
     * @return The dataCriacao.
     */
    public java.lang.String getDataCriacao() {
      java.lang.Object ref = dataCriacao_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataCriacao_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataCriacao = 4;</code>
     * @return The bytes for dataCriacao.
     */
    public com.google.protobuf.ByteString
        getDataCriacaoBytes() {
      java.lang.Object ref = dataCriacao_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataCriacao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataCriacao = 4;</code>
     * @param value The dataCriacao to set.
     * @return This builder for chaining.
     */
    public Builder setDataCriacao(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataCriacao_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string dataCriacao = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataCriacao() {
      dataCriacao_ = getDefaultInstance().getDataCriacao();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string dataCriacao = 4;</code>
     * @param value The bytes for dataCriacao to set.
     * @return This builder for chaining.
     */
    public Builder setDataCriacaoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataCriacao_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.Carteira)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.Carteira)
  private static final br.ufc.ds.trabalho2.protobuf.Carteira DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.Carteira();
  }

  public static br.ufc.ds.trabalho2.protobuf.Carteira getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Carteira>
      PARSER = new com.google.protobuf.AbstractParser<Carteira>() {
    @java.lang.Override
    public Carteira parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Carteira> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Carteira> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.Carteira getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

