// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface CarteiraOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.Carteira)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string carteiraId = 1;</code>
   * @return The carteiraId.
   */
  java.lang.String getCarteiraId();
  /**
   * <code>string carteiraId = 1;</code>
   * @return The bytes for carteiraId.
   */
  com.google.protobuf.ByteString
      getCarteiraIdBytes();

  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  int getAtivosCount();
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  boolean containsAtivos(
      java.lang.String key);
  /**
   * Use {@link #getAtivosMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getAtivos();
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getAtivosMap();
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  long getAtivosOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <pre>
   * ticker -&gt; quantidade
   * </pre>
   *
   * <code>map&lt;string, int64&gt; ativos = 2;</code>
   */
  long getAtivosOrThrow(
      java.lang.String key);

  /**
   * <code>double saldoDisponivel = 3;</code>
   * @return The saldoDisponivel.
   */
  double getSaldoDisponivel();

  /**
   * <code>string dataCriacao = 4;</code>
   * @return The dataCriacao.
   */
  java.lang.String getDataCriacao();
  /**
   * <code>string dataCriacao = 4;</code>
   * @return The bytes for dataCriacao.
   */
  com.google.protobuf.ByteString
      getDataCriacaoBytes();
}
