// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface ContaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.Conta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contaId = 1;</code>
   * @return The contaId.
   */
  java.lang.String getContaId();
  /**
   * <code>string contaId = 1;</code>
   * @return The bytes for contaId.
   */
  com.google.protobuf.ByteString
      getContaIdBytes();

  /**
   * <code>string investidorId = 2;</code>
   * @return The investidorId.
   */
  java.lang.String getInvestidorId();
  /**
   * <code>string investidorId = 2;</code>
   * @return The bytes for investidorId.
   */
  com.google.protobuf.ByteString
      getInvestidorIdBytes();

  /**
   * <code>string banco = 3;</code>
   * @return The banco.
   */
  java.lang.String getBanco();
  /**
   * <code>string banco = 3;</code>
   * @return The bytes for banco.
   */
  com.google.protobuf.ByteString
      getBancoBytes();

  /**
   * <code>string agencia = 4;</code>
   * @return The agencia.
   */
  java.lang.String getAgencia();
  /**
   * <code>string agencia = 4;</code>
   * @return The bytes for agencia.
   */
  com.google.protobuf.ByteString
      getAgenciaBytes();

  /**
   * <code>string numeroConta = 5;</code>
   * @return The numeroConta.
   */
  java.lang.String getNumeroConta();
  /**
   * <code>string numeroConta = 5;</code>
   * @return The bytes for numeroConta.
   */
  com.google.protobuf.ByteString
      getNumeroContaBytes();

  /**
   * <code>string tipoConta = 6;</code>
   * @return The tipoConta.
   */
  java.lang.String getTipoConta();
  /**
   * <code>string tipoConta = 6;</code>
   * @return The bytes for tipoConta.
   */
  com.google.protobuf.ByteString
      getTipoContaBytes();

  /**
   * <code>double saldo = 7;</code>
   * @return The saldo.
   */
  double getSaldo();

  /**
   * <code>string dataAbertura = 8;</code>
   * @return The dataAbertura.
   */
  java.lang.String getDataAbertura();
  /**
   * <code>string dataAbertura = 8;</code>
   * @return The bytes for dataAbertura.
   */
  com.google.protobuf.ByteString
      getDataAberturaBytes();
}
