// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Conta}
 */
@com.google.protobuf.Generated
public final class Conta extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.Conta)
    ContaOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Conta");
  }
  // Use Conta.newBuilder() to construct.
  private Conta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Conta() {
    contaId_ = "";
    investidorId_ = "";
    banco_ = "";
    agencia_ = "";
    numeroConta_ = "";
    tipoConta_ = "";
    dataAbertura_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Conta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.Conta.class, br.ufc.ds.trabalho2.protobuf.Conta.Builder.class);
  }

  public static final int CONTAID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contaId_ = "";
  /**
   * <code>string contaId = 1;</code>
   * @return The contaId.
   */
  @java.lang.Override
  public java.lang.String getContaId() {
    java.lang.Object ref = contaId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contaId_ = s;
      return s;
    }
  }
  /**
   * <code>string contaId = 1;</code>
   * @return The bytes for contaId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContaIdBytes() {
    java.lang.Object ref = contaId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contaId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVESTIDORID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object investidorId_ = "";
  /**
   * <code>string investidorId = 2;</code>
   * @return The investidorId.
   */
  @java.lang.Override
  public java.lang.String getInvestidorId() {
    java.lang.Object ref = investidorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      investidorId_ = s;
      return s;
    }
  }
  /**
   * <code>string investidorId = 2;</code>
   * @return The bytes for investidorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvestidorIdBytes() {
    java.lang.Object ref = investidorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      investidorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANCO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object banco_ = "";
  /**
   * <code>string banco = 3;</code>
   * @return The banco.
   */
  @java.lang.Override
  public java.lang.String getBanco() {
    java.lang.Object ref = banco_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      banco_ = s;
      return s;
    }
  }
  /**
   * <code>string banco = 3;</code>
   * @return The bytes for banco.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBancoBytes() {
    java.lang.Object ref = banco_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      banco_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENCIA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agencia_ = "";
  /**
   * <code>string agencia = 4;</code>
   * @return The agencia.
   */
  @java.lang.Override
  public java.lang.String getAgencia() {
    java.lang.Object ref = agencia_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agencia_ = s;
      return s;
    }
  }
  /**
   * <code>string agencia = 4;</code>
   * @return The bytes for agencia.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgenciaBytes() {
    java.lang.Object ref = agencia_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agencia_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMEROCONTA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object numeroConta_ = "";
  /**
   * <code>string numeroConta = 5;</code>
   * @return The numeroConta.
   */
  @java.lang.Override
  public java.lang.String getNumeroConta() {
    java.lang.Object ref = numeroConta_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      numeroConta_ = s;
      return s;
    }
  }
  /**
   * <code>string numeroConta = 5;</code>
   * @return The bytes for numeroConta.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNumeroContaBytes() {
    java.lang.Object ref = numeroConta_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      numeroConta_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIPOCONTA_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tipoConta_ = "";
  /**
   * <code>string tipoConta = 6;</code>
   * @return The tipoConta.
   */
  @java.lang.Override
  public java.lang.String getTipoConta() {
    java.lang.Object ref = tipoConta_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipoConta_ = s;
      return s;
    }
  }
  /**
   * <code>string tipoConta = 6;</code>
   * @return The bytes for tipoConta.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipoContaBytes() {
    java.lang.Object ref = tipoConta_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipoConta_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALDO_FIELD_NUMBER = 7;
  private double saldo_ = 0D;
  /**
   * <code>double saldo = 7;</code>
   * @return The saldo.
   */
  @java.lang.Override
  public double getSaldo() {
    return saldo_;
  }

  public static final int DATAABERTURA_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataAbertura_ = "";
  /**
   * <code>string dataAbertura = 8;</code>
   * @return The dataAbertura.
   */
  @java.lang.Override
  public java.lang.String getDataAbertura() {
    java.lang.Object ref = dataAbertura_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataAbertura_ = s;
      return s;
    }
  }
  /**
   * <code>string dataAbertura = 8;</code>
   * @return The bytes for dataAbertura.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataAberturaBytes() {
    java.lang.Object ref = dataAbertura_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataAbertura_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contaId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, contaId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(investidorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, investidorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(banco_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, banco_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agencia_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, agencia_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(numeroConta_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, numeroConta_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipoConta_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, tipoConta_);
    }
    if (java.lang.Double.doubleToRawLongBits(saldo_) != 0) {
      output.writeDouble(7, saldo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataAbertura_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, dataAbertura_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contaId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contaId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(investidorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, investidorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(banco_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, banco_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agencia_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, agencia_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(numeroConta_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, numeroConta_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipoConta_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, tipoConta_);
    }
    if (java.lang.Double.doubleToRawLongBits(saldo_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, saldo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataAbertura_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, dataAbertura_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.Conta)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.Conta other = (br.ufc.ds.trabalho2.protobuf.Conta) obj;

    if (!getContaId()
        .equals(other.getContaId())) return false;
    if (!getInvestidorId()
        .equals(other.getInvestidorId())) return false;
    if (!getBanco()
        .equals(other.getBanco())) return false;
    if (!getAgencia()
        .equals(other.getAgencia())) return false;
    if (!getNumeroConta()
        .equals(other.getNumeroConta())) return false;
    if (!getTipoConta()
        .equals(other.getTipoConta())) return false;
    if (java.lang.Double.doubleToLongBits(getSaldo())
        != java.lang.Double.doubleToLongBits(
            other.getSaldo())) return false;
    if (!getDataAbertura()
        .equals(other.getDataAbertura())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTAID_FIELD_NUMBER;
    hash = (53 * hash) + getContaId().hashCode();
    hash = (37 * hash) + INVESTIDORID_FIELD_NUMBER;
    hash = (53 * hash) + getInvestidorId().hashCode();
    hash = (37 * hash) + BANCO_FIELD_NUMBER;
    hash = (53 * hash) + getBanco().hashCode();
    hash = (37 * hash) + AGENCIA_FIELD_NUMBER;
    hash = (53 * hash) + getAgencia().hashCode();
    hash = (37 * hash) + NUMEROCONTA_FIELD_NUMBER;
    hash = (53 * hash) + getNumeroConta().hashCode();
    hash = (37 * hash) + TIPOCONTA_FIELD_NUMBER;
    hash = (53 * hash) + getTipoConta().hashCode();
    hash = (37 * hash) + SALDO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSaldo()));
    hash = (37 * hash) + DATAABERTURA_FIELD_NUMBER;
    hash = (53 * hash) + getDataAbertura().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.Conta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.Conta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Conta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.Conta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Conta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.Conta)
      br.ufc.ds.trabalho2.protobuf.ContaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Conta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.Conta.class, br.ufc.ds.trabalho2.protobuf.Conta.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.Conta.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contaId_ = "";
      investidorId_ = "";
      banco_ = "";
      agencia_ = "";
      numeroConta_ = "";
      tipoConta_ = "";
      saldo_ = 0D;
      dataAbertura_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Conta getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.Conta.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Conta build() {
      br.ufc.ds.trabalho2.protobuf.Conta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Conta buildPartial() {
      br.ufc.ds.trabalho2.protobuf.Conta result = new br.ufc.ds.trabalho2.protobuf.Conta(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.Conta result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contaId_ = contaId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.investidorId_ = investidorId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.banco_ = banco_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.agencia_ = agencia_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.numeroConta_ = numeroConta_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tipoConta_ = tipoConta_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.saldo_ = saldo_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.dataAbertura_ = dataAbertura_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.Conta) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.Conta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.Conta other) {
      if (other == br.ufc.ds.trabalho2.protobuf.Conta.getDefaultInstance()) return this;
      if (!other.getContaId().isEmpty()) {
        contaId_ = other.contaId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getInvestidorId().isEmpty()) {
        investidorId_ = other.investidorId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBanco().isEmpty()) {
        banco_ = other.banco_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAgencia().isEmpty()) {
        agencia_ = other.agencia_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getNumeroConta().isEmpty()) {
        numeroConta_ = other.numeroConta_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTipoConta().isEmpty()) {
        tipoConta_ = other.tipoConta_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getSaldo()) != 0) {
        setSaldo(other.getSaldo());
      }
      if (!other.getDataAbertura().isEmpty()) {
        dataAbertura_ = other.dataAbertura_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contaId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              investidorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              banco_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              agencia_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              numeroConta_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              tipoConta_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 57: {
              saldo_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 66: {
              dataAbertura_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contaId_ = "";
    /**
     * <code>string contaId = 1;</code>
     * @return The contaId.
     */
    public java.lang.String getContaId() {
      java.lang.Object ref = contaId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contaId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contaId = 1;</code>
     * @return The bytes for contaId.
     */
    public com.google.protobuf.ByteString
        getContaIdBytes() {
      java.lang.Object ref = contaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contaId = 1;</code>
     * @param value The contaId to set.
     * @return This builder for chaining.
     */
    public Builder setContaId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contaId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contaId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContaId() {
      contaId_ = getDefaultInstance().getContaId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contaId = 1;</code>
     * @param value The bytes for contaId to set.
     * @return This builder for chaining.
     */
    public Builder setContaIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contaId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object investidorId_ = "";
    /**
     * <code>string investidorId = 2;</code>
     * @return The investidorId.
     */
    public java.lang.String getInvestidorId() {
      java.lang.Object ref = investidorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        investidorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string investidorId = 2;</code>
     * @return The bytes for investidorId.
     */
    public com.google.protobuf.ByteString
        getInvestidorIdBytes() {
      java.lang.Object ref = investidorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        investidorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string investidorId = 2;</code>
     * @param value The investidorId to set.
     * @return This builder for chaining.
     */
    public Builder setInvestidorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      investidorId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string investidorId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvestidorId() {
      investidorId_ = getDefaultInstance().getInvestidorId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string investidorId = 2;</code>
     * @param value The bytes for investidorId to set.
     * @return This builder for chaining.
     */
    public Builder setInvestidorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      investidorId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object banco_ = "";
    /**
     * <code>string banco = 3;</code>
     * @return The banco.
     */
    public java.lang.String getBanco() {
      java.lang.Object ref = banco_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        banco_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string banco = 3;</code>
     * @return The bytes for banco.
     */
    public com.google.protobuf.ByteString
        getBancoBytes() {
      java.lang.Object ref = banco_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        banco_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string banco = 3;</code>
     * @param value The banco to set.
     * @return This builder for chaining.
     */
    public Builder setBanco(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      banco_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string banco = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBanco() {
      banco_ = getDefaultInstance().getBanco();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string banco = 3;</code>
     * @param value The bytes for banco to set.
     * @return This builder for chaining.
     */
    public Builder setBancoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      banco_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object agencia_ = "";
    /**
     * <code>string agencia = 4;</code>
     * @return The agencia.
     */
    public java.lang.String getAgencia() {
      java.lang.Object ref = agencia_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agencia_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agencia = 4;</code>
     * @return The bytes for agencia.
     */
    public com.google.protobuf.ByteString
        getAgenciaBytes() {
      java.lang.Object ref = agencia_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agencia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agencia = 4;</code>
     * @param value The agencia to set.
     * @return This builder for chaining.
     */
    public Builder setAgencia(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agencia_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string agencia = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgencia() {
      agencia_ = getDefaultInstance().getAgencia();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string agencia = 4;</code>
     * @param value The bytes for agencia to set.
     * @return This builder for chaining.
     */
    public Builder setAgenciaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agencia_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object numeroConta_ = "";
    /**
     * <code>string numeroConta = 5;</code>
     * @return The numeroConta.
     */
    public java.lang.String getNumeroConta() {
      java.lang.Object ref = numeroConta_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numeroConta_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string numeroConta = 5;</code>
     * @return The bytes for numeroConta.
     */
    public com.google.protobuf.ByteString
        getNumeroContaBytes() {
      java.lang.Object ref = numeroConta_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numeroConta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string numeroConta = 5;</code>
     * @param value The numeroConta to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroConta(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      numeroConta_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string numeroConta = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumeroConta() {
      numeroConta_ = getDefaultInstance().getNumeroConta();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string numeroConta = 5;</code>
     * @param value The bytes for numeroConta to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroContaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      numeroConta_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object tipoConta_ = "";
    /**
     * <code>string tipoConta = 6;</code>
     * @return The tipoConta.
     */
    public java.lang.String getTipoConta() {
      java.lang.Object ref = tipoConta_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipoConta_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tipoConta = 6;</code>
     * @return The bytes for tipoConta.
     */
    public com.google.protobuf.ByteString
        getTipoContaBytes() {
      java.lang.Object ref = tipoConta_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipoConta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tipoConta = 6;</code>
     * @param value The tipoConta to set.
     * @return This builder for chaining.
     */
    public Builder setTipoConta(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tipoConta_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string tipoConta = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipoConta() {
      tipoConta_ = getDefaultInstance().getTipoConta();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string tipoConta = 6;</code>
     * @param value The bytes for tipoConta to set.
     * @return This builder for chaining.
     */
    public Builder setTipoContaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tipoConta_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private double saldo_ ;
    /**
     * <code>double saldo = 7;</code>
     * @return The saldo.
     */
    @java.lang.Override
    public double getSaldo() {
      return saldo_;
    }
    /**
     * <code>double saldo = 7;</code>
     * @param value The saldo to set.
     * @return This builder for chaining.
     */
    public Builder setSaldo(double value) {

      saldo_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double saldo = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaldo() {
      bitField0_ = (bitField0_ & ~0x00000040);
      saldo_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object dataAbertura_ = "";
    /**
     * <code>string dataAbertura = 8;</code>
     * @return The dataAbertura.
     */
    public java.lang.String getDataAbertura() {
      java.lang.Object ref = dataAbertura_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataAbertura_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataAbertura = 8;</code>
     * @return The bytes for dataAbertura.
     */
    public com.google.protobuf.ByteString
        getDataAberturaBytes() {
      java.lang.Object ref = dataAbertura_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataAbertura_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataAbertura = 8;</code>
     * @param value The dataAbertura to set.
     * @return This builder for chaining.
     */
    public Builder setDataAbertura(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataAbertura_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string dataAbertura = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataAbertura() {
      dataAbertura_ = getDefaultInstance().getDataAbertura();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string dataAbertura = 8;</code>
     * @param value The bytes for dataAbertura to set.
     * @return This builder for chaining.
     */
    public Builder setDataAberturaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataAbertura_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.Conta)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.Conta)
  private static final br.ufc.ds.trabalho2.protobuf.Conta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.Conta();
  }

  public static br.ufc.ds.trabalho2.protobuf.Conta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Conta>
      PARSER = new com.google.protobuf.AbstractParser<Conta>() {
    @java.lang.Override
    public Conta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Conta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Conta> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.Conta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

