// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface InvestidorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.Investidor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string investidorId = 1;</code>
   * @return The investidorId.
   */
  java.lang.String getInvestidorId();
  /**
   * <code>string investidorId = 1;</code>
   * @return The bytes for investidorId.
   */
  com.google.protobuf.ByteString
      getInvestidorIdBytes();

  /**
   * <code>string nome = 2;</code>
   * @return The nome.
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 2;</code>
   * @return The bytes for nome.
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>string cpf = 3;</code>
   * @return The cpf.
   */
  java.lang.String getCpf();
  /**
   * <code>string cpf = 3;</code>
   * @return The bytes for cpf.
   */
  com.google.protobuf.ByteString
      getCpfBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string telefone = 5;</code>
   * @return The telefone.
   */
  java.lang.String getTelefone();
  /**
   * <code>string telefone = 5;</code>
   * @return The bytes for telefone.
   */
  com.google.protobuf.ByteString
      getTelefoneBytes();

  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
   * @return Whether the carteira field is set.
   */
  boolean hasCarteira();
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
   * @return The carteira.
   */
  br.ufc.ds.trabalho2.protobuf.Carteira getCarteira();
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
   */
  br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder getCarteiraOrBuilder();

  /**
   * <code>string dataCadastro = 7;</code>
   * @return The dataCadastro.
   */
  java.lang.String getDataCadastro();
  /**
   * <code>string dataCadastro = 7;</code>
   * @return The bytes for dataCadastro.
   */
  com.google.protobuf.ByteString
      getDataCadastroBytes();
}
