// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Investidor}
 */
@com.google.protobuf.Generated
public final class Investidor extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.Investidor)
    InvestidorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Investidor");
  }
  // Use Investidor.newBuilder() to construct.
  private Investidor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Investidor() {
    investidorId_ = "";
    nome_ = "";
    cpf_ = "";
    email_ = "";
    telefone_ = "";
    dataCadastro_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.Investidor.class, br.ufc.ds.trabalho2.protobuf.Investidor.Builder.class);
  }

  private int bitField0_;
  public static final int INVESTIDORID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object investidorId_ = "";
  /**
   * <code>string investidorId = 1;</code>
   * @return The investidorId.
   */
  @java.lang.Override
  public java.lang.String getInvestidorId() {
    java.lang.Object ref = investidorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      investidorId_ = s;
      return s;
    }
  }
  /**
   * <code>string investidorId = 1;</code>
   * @return The bytes for investidorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvestidorIdBytes() {
    java.lang.Object ref = investidorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      investidorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nome_ = "";
  /**
   * <code>string nome = 2;</code>
   * @return The nome.
   */
  @java.lang.Override
  public java.lang.String getNome() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nome_ = s;
      return s;
    }
  }
  /**
   * <code>string nome = 2;</code>
   * @return The bytes for nome.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeBytes() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPF_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cpf_ = "";
  /**
   * <code>string cpf = 3;</code>
   * @return The cpf.
   */
  @java.lang.Override
  public java.lang.String getCpf() {
    java.lang.Object ref = cpf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpf_ = s;
      return s;
    }
  }
  /**
   * <code>string cpf = 3;</code>
   * @return The bytes for cpf.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCpfBytes() {
    java.lang.Object ref = cpf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEFONE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object telefone_ = "";
  /**
   * <code>string telefone = 5;</code>
   * @return The telefone.
   */
  @java.lang.Override
  public java.lang.String getTelefone() {
    java.lang.Object ref = telefone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      telefone_ = s;
      return s;
    }
  }
  /**
   * <code>string telefone = 5;</code>
   * @return The bytes for telefone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTelefoneBytes() {
    java.lang.Object ref = telefone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      telefone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARTEIRA_FIELD_NUMBER = 6;
  private br.ufc.ds.trabalho2.protobuf.Carteira carteira_;
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
   * @return Whether the carteira field is set.
   */
  @java.lang.Override
  public boolean hasCarteira() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
   * @return The carteira.
   */
  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.Carteira getCarteira() {
    return carteira_ == null ? br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance() : carteira_;
  }
  /**
   * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
   */
  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder getCarteiraOrBuilder() {
    return carteira_ == null ? br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance() : carteira_;
  }

  public static final int DATACADASTRO_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataCadastro_ = "";
  /**
   * <code>string dataCadastro = 7;</code>
   * @return The dataCadastro.
   */
  @java.lang.Override
  public java.lang.String getDataCadastro() {
    java.lang.Object ref = dataCadastro_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataCadastro_ = s;
      return s;
    }
  }
  /**
   * <code>string dataCadastro = 7;</code>
   * @return The bytes for dataCadastro.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataCadastroBytes() {
    java.lang.Object ref = dataCadastro_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataCadastro_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(investidorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, investidorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nome_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cpf_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, cpf_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, email_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(telefone_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, telefone_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getCarteira());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataCadastro_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, dataCadastro_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(investidorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, investidorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nome_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cpf_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, cpf_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, email_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(telefone_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, telefone_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCarteira());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataCadastro_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, dataCadastro_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.Investidor)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.Investidor other = (br.ufc.ds.trabalho2.protobuf.Investidor) obj;

    if (!getInvestidorId()
        .equals(other.getInvestidorId())) return false;
    if (!getNome()
        .equals(other.getNome())) return false;
    if (!getCpf()
        .equals(other.getCpf())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getTelefone()
        .equals(other.getTelefone())) return false;
    if (hasCarteira() != other.hasCarteira()) return false;
    if (hasCarteira()) {
      if (!getCarteira()
          .equals(other.getCarteira())) return false;
    }
    if (!getDataCadastro()
        .equals(other.getDataCadastro())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INVESTIDORID_FIELD_NUMBER;
    hash = (53 * hash) + getInvestidorId().hashCode();
    hash = (37 * hash) + NOME_FIELD_NUMBER;
    hash = (53 * hash) + getNome().hashCode();
    hash = (37 * hash) + CPF_FIELD_NUMBER;
    hash = (53 * hash) + getCpf().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + TELEFONE_FIELD_NUMBER;
    hash = (53 * hash) + getTelefone().hashCode();
    if (hasCarteira()) {
      hash = (37 * hash) + CARTEIRA_FIELD_NUMBER;
      hash = (53 * hash) + getCarteira().hashCode();
    }
    hash = (37 * hash) + DATACADASTRO_FIELD_NUMBER;
    hash = (53 * hash) + getDataCadastro().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.Investidor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.Investidor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.Investidor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.Investidor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.Investidor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.Investidor)
      br.ufc.ds.trabalho2.protobuf.InvestidorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.Investidor.class, br.ufc.ds.trabalho2.protobuf.Investidor.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.Investidor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCarteiraFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      investidorId_ = "";
      nome_ = "";
      cpf_ = "";
      email_ = "";
      telefone_ = "";
      carteira_ = null;
      if (carteiraBuilder_ != null) {
        carteiraBuilder_.dispose();
        carteiraBuilder_ = null;
      }
      dataCadastro_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Investidor getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.Investidor.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Investidor build() {
      br.ufc.ds.trabalho2.protobuf.Investidor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.Investidor buildPartial() {
      br.ufc.ds.trabalho2.protobuf.Investidor result = new br.ufc.ds.trabalho2.protobuf.Investidor(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.Investidor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.investidorId_ = investidorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nome_ = nome_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cpf_ = cpf_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.telefone_ = telefone_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.carteira_ = carteiraBuilder_ == null
            ? carteira_
            : carteiraBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.dataCadastro_ = dataCadastro_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.Investidor) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.Investidor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.Investidor other) {
      if (other == br.ufc.ds.trabalho2.protobuf.Investidor.getDefaultInstance()) return this;
      if (!other.getInvestidorId().isEmpty()) {
        investidorId_ = other.investidorId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNome().isEmpty()) {
        nome_ = other.nome_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCpf().isEmpty()) {
        cpf_ = other.cpf_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTelefone().isEmpty()) {
        telefone_ = other.telefone_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasCarteira()) {
        mergeCarteira(other.getCarteira());
      }
      if (!other.getDataCadastro().isEmpty()) {
        dataCadastro_ = other.dataCadastro_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              investidorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nome_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              cpf_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              telefone_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetCarteiraFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              dataCadastro_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object investidorId_ = "";
    /**
     * <code>string investidorId = 1;</code>
     * @return The investidorId.
     */
    public java.lang.String getInvestidorId() {
      java.lang.Object ref = investidorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        investidorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string investidorId = 1;</code>
     * @return The bytes for investidorId.
     */
    public com.google.protobuf.ByteString
        getInvestidorIdBytes() {
      java.lang.Object ref = investidorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        investidorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string investidorId = 1;</code>
     * @param value The investidorId to set.
     * @return This builder for chaining.
     */
    public Builder setInvestidorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      investidorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string investidorId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvestidorId() {
      investidorId_ = getDefaultInstance().getInvestidorId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string investidorId = 1;</code>
     * @param value The bytes for investidorId to set.
     * @return This builder for chaining.
     */
    public Builder setInvestidorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      investidorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object nome_ = "";
    /**
     * <code>string nome = 2;</code>
     * @return The nome.
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nome = 2;</code>
     * @return The bytes for nome.
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nome = 2;</code>
     * @param value The nome to set.
     * @return This builder for chaining.
     */
    public Builder setNome(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nome_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string nome = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNome() {
      nome_ = getDefaultInstance().getNome();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string nome = 2;</code>
     * @param value The bytes for nome to set.
     * @return This builder for chaining.
     */
    public Builder setNomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nome_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object cpf_ = "";
    /**
     * <code>string cpf = 3;</code>
     * @return The cpf.
     */
    public java.lang.String getCpf() {
      java.lang.Object ref = cpf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cpf = 3;</code>
     * @return The bytes for cpf.
     */
    public com.google.protobuf.ByteString
        getCpfBytes() {
      java.lang.Object ref = cpf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cpf = 3;</code>
     * @param value The cpf to set.
     * @return This builder for chaining.
     */
    public Builder setCpf(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cpf_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string cpf = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpf() {
      cpf_ = getDefaultInstance().getCpf();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string cpf = 3;</code>
     * @param value The bytes for cpf to set.
     * @return This builder for chaining.
     */
    public Builder setCpfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cpf_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object telefone_ = "";
    /**
     * <code>string telefone = 5;</code>
     * @return The telefone.
     */
    public java.lang.String getTelefone() {
      java.lang.Object ref = telefone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telefone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string telefone = 5;</code>
     * @return The bytes for telefone.
     */
    public com.google.protobuf.ByteString
        getTelefoneBytes() {
      java.lang.Object ref = telefone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telefone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string telefone = 5;</code>
     * @param value The telefone to set.
     * @return This builder for chaining.
     */
    public Builder setTelefone(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      telefone_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string telefone = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelefone() {
      telefone_ = getDefaultInstance().getTelefone();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string telefone = 5;</code>
     * @param value The bytes for telefone to set.
     * @return This builder for chaining.
     */
    public Builder setTelefoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      telefone_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private br.ufc.ds.trabalho2.protobuf.Carteira carteira_;
    private com.google.protobuf.SingleFieldBuilder<
        br.ufc.ds.trabalho2.protobuf.Carteira, br.ufc.ds.trabalho2.protobuf.Carteira.Builder, br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder> carteiraBuilder_;
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     * @return Whether the carteira field is set.
     */
    public boolean hasCarteira() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     * @return The carteira.
     */
    public br.ufc.ds.trabalho2.protobuf.Carteira getCarteira() {
      if (carteiraBuilder_ == null) {
        return carteira_ == null ? br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance() : carteira_;
      } else {
        return carteiraBuilder_.getMessage();
      }
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    public Builder setCarteira(br.ufc.ds.trabalho2.protobuf.Carteira value) {
      if (carteiraBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        carteira_ = value;
      } else {
        carteiraBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    public Builder setCarteira(
        br.ufc.ds.trabalho2.protobuf.Carteira.Builder builderForValue) {
      if (carteiraBuilder_ == null) {
        carteira_ = builderForValue.build();
      } else {
        carteiraBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    public Builder mergeCarteira(br.ufc.ds.trabalho2.protobuf.Carteira value) {
      if (carteiraBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          carteira_ != null &&
          carteira_ != br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance()) {
          getCarteiraBuilder().mergeFrom(value);
        } else {
          carteira_ = value;
        }
      } else {
        carteiraBuilder_.mergeFrom(value);
      }
      if (carteira_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    public Builder clearCarteira() {
      bitField0_ = (bitField0_ & ~0x00000020);
      carteira_ = null;
      if (carteiraBuilder_ != null) {
        carteiraBuilder_.dispose();
        carteiraBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    public br.ufc.ds.trabalho2.protobuf.Carteira.Builder getCarteiraBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetCarteiraFieldBuilder().getBuilder();
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    public br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder getCarteiraOrBuilder() {
      if (carteiraBuilder_ != null) {
        return carteiraBuilder_.getMessageOrBuilder();
      } else {
        return carteira_ == null ?
            br.ufc.ds.trabalho2.protobuf.Carteira.getDefaultInstance() : carteira_;
      }
    }
    /**
     * <code>.br.ufc.ds.trabalho2.protobuf.Carteira carteira = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        br.ufc.ds.trabalho2.protobuf.Carteira, br.ufc.ds.trabalho2.protobuf.Carteira.Builder, br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder> 
        internalGetCarteiraFieldBuilder() {
      if (carteiraBuilder_ == null) {
        carteiraBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            br.ufc.ds.trabalho2.protobuf.Carteira, br.ufc.ds.trabalho2.protobuf.Carteira.Builder, br.ufc.ds.trabalho2.protobuf.CarteiraOrBuilder>(
                getCarteira(),
                getParentForChildren(),
                isClean());
        carteira_ = null;
      }
      return carteiraBuilder_;
    }

    private java.lang.Object dataCadastro_ = "";
    /**
     * <code>string dataCadastro = 7;</code>
     * @return The dataCadastro.
     */
    public java.lang.String getDataCadastro() {
      java.lang.Object ref = dataCadastro_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataCadastro_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataCadastro = 7;</code>
     * @return The bytes for dataCadastro.
     */
    public com.google.protobuf.ByteString
        getDataCadastroBytes() {
      java.lang.Object ref = dataCadastro_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataCadastro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataCadastro = 7;</code>
     * @param value The dataCadastro to set.
     * @return This builder for chaining.
     */
    public Builder setDataCadastro(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataCadastro_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string dataCadastro = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataCadastro() {
      dataCadastro_ = getDefaultInstance().getDataCadastro();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string dataCadastro = 7;</code>
     * @param value The bytes for dataCadastro to set.
     * @return This builder for chaining.
     */
    public Builder setDataCadastroBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataCadastro_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.Investidor)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.Investidor)
  private static final br.ufc.ds.trabalho2.protobuf.Investidor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.Investidor();
  }

  public static br.ufc.ds.trabalho2.protobuf.Investidor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Investidor>
      PARSER = new com.google.protobuf.AbstractParser<Investidor>() {
    @java.lang.Override
    public Investidor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Investidor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Investidor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.Investidor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

