// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public final class ModelProto extends com.google.protobuf.GeneratedFile {
  private ModelProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ModelProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_AtivoB3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_AtivoB3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_AtivosEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_AtivosEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_Conta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\034br.ufc.ds.trabalho2.proto" +
      "buf\"\325\001\n\005Ativo\022\016\n\006ticker\030\001 \001(\t\022\022\n\nprecoAt" +
      "ual\030\002 \001(\001\022\021\n\tdescricao\030\003 \001(\t\022\014\n\004tipo\030\004 \001" +
      "(\t\0228\n\007ativoB3\030\005 \001(\0132%.br.ufc.ds.trabalho" +
      "2.protobuf.AtivoB3H\000\022<\n\tativoFixo\030\006 \001(\0132" +
      "\'.br.ufc.ds.trabalho2.protobuf.AtivoFixo" +
      "H\000B\017\n\rtipoSpecifico\"k\n\007AtivoB3\022\016\n\006ticker" +
      "\030\001 \001(\t\022\022\n\nprecoAtual\030\002 \001(\001\022\021\n\tdescricao\030" +
      "\003 \001(\t\022\020\n\010segmento\030\004 \001(\t\022\027\n\017volumeNegocia" +
      "do\030\005 \001(\003\"m\n\tAtivoFixo\022\016\n\006ticker\030\001 \001(\t\022\022\n" +
      "\nprecoAtual\030\002 \001(\001\022\021\n\tdescricao\030\003 \001(\t\022\021\n\t" +
      "taxaJuros\030\004 \001(\001\022\026\n\016dataVencimento\030\005 \001(\t\"" +
      "\246\001\n\021OrdemInvestimento\022\017\n\007ordemId\030\001 \001(\t\022\014" +
      "\n\004tipo\030\002 \001(\t\022\016\n\006ticker\030\003 \001(\t\022\022\n\nquantida" +
      "de\030\004 \001(\003\022\025\n\rprecoUnitario\030\005 \001(\001\022\022\n\npreco" +
      "Total\030\006 \001(\001\022\016\n\006status\030\007 \001(\t\022\023\n\013dataCriac" +
      "ao\030\010 \001(\t\"\277\001\n\010Carteira\022\022\n\ncarteiraId\030\001 \001(" +
      "\t\022B\n\006ativos\030\002 \003(\01322.br.ufc.ds.trabalho2." +
      "protobuf.Carteira.AtivosEntry\022\027\n\017saldoDi" +
      "sponivel\030\003 \001(\001\022\023\n\013dataCriacao\030\004 \001(\t\032-\n\013A" +
      "tivosEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\003:\002" +
      "8\001\"\256\001\n\nInvestidor\022\024\n\014investidorId\030\001 \001(\t\022" +
      "\014\n\004nome\030\002 \001(\t\022\013\n\003cpf\030\003 \001(\t\022\r\n\005email\030\004 \001(" +
      "\t\022\020\n\010telefone\030\005 \001(\t\0228\n\010carteira\030\006 \001(\0132&." +
      "br.ufc.ds.trabalho2.protobuf.Carteira\022\024\n" +
      "\014dataCadastro\030\007 \001(\t\"\233\001\n\005Conta\022\017\n\007contaId" +
      "\030\001 \001(\t\022\024\n\014investidorId\030\002 \001(\t\022\r\n\005banco\030\003 " +
      "\001(\t\022\017\n\007agencia\030\004 \001(\t\022\023\n\013numeroConta\030\005 \001(" +
      "\t\022\021\n\ttipoConta\030\006 \001(\t\022\r\n\005saldo\030\007 \001(\001\022\024\n\014d" +
      "ataAbertura\030\010 \001(\tB,\n\034br.ufc.ds.trabalho2" +
      ".protobufB\nModelProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_Ativo_descriptor,
        new java.lang.String[] { "Ticker", "PrecoAtual", "Descricao", "Tipo", "AtivoB3", "AtivoFixo", "TipoSpecifico", });
    internal_static_br_ufc_ds_trabalho2_protobuf_AtivoB3_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_br_ufc_ds_trabalho2_protobuf_AtivoB3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_AtivoB3_descriptor,
        new java.lang.String[] { "Ticker", "PrecoAtual", "Descricao", "Segmento", "VolumeNegociado", });
    internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_AtivoFixo_descriptor,
        new java.lang.String[] { "Ticker", "PrecoAtual", "Descricao", "TaxaJuros", "DataVencimento", });
    internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor,
        new java.lang.String[] { "OrdemId", "Tipo", "Ticker", "Quantidade", "PrecoUnitario", "PrecoTotal", "Status", "DataCriacao", });
    internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor,
        new java.lang.String[] { "CarteiraId", "Ativos", "SaldoDisponivel", "DataCriacao", });
    internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_AtivosEntry_descriptor =
      internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_descriptor.getNestedType(0);
    internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_AtivosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_Carteira_AtivosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_Investidor_descriptor,
        new java.lang.String[] { "InvestidorId", "Nome", "Cpf", "Email", "Telefone", "Carteira", "DataCadastro", });
    internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_br_ufc_ds_trabalho2_protobuf_Conta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_Conta_descriptor,
        new java.lang.String[] { "ContaId", "InvestidorId", "Banco", "Agencia", "NumeroConta", "TipoConta", "Saldo", "DataAbertura", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
