// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.OrdemInvestimento}
 */
@com.google.protobuf.Generated
public final class OrdemInvestimento extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)
    OrdemInvestimentoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "OrdemInvestimento");
  }
  // Use OrdemInvestimento.newBuilder() to construct.
  private OrdemInvestimento(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OrdemInvestimento() {
    ordemId_ = "";
    tipo_ = "";
    ticker_ = "";
    status_ = "";
    dataCriacao_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.class, br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.Builder.class);
  }

  public static final int ORDEMID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ordemId_ = "";
  /**
   * <code>string ordemId = 1;</code>
   * @return The ordemId.
   */
  @java.lang.Override
  public java.lang.String getOrdemId() {
    java.lang.Object ref = ordemId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ordemId_ = s;
      return s;
    }
  }
  /**
   * <code>string ordemId = 1;</code>
   * @return The bytes for ordemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrdemIdBytes() {
    java.lang.Object ref = ordemId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ordemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIPO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tipo_ = "";
  /**
   * <pre>
   * COMPRA, VENDA
   * </pre>
   *
   * <code>string tipo = 2;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public java.lang.String getTipo() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * COMPRA, VENDA
   * </pre>
   *
   * <code>string tipo = 2;</code>
   * @return The bytes for tipo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipoBytes() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TICKER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ticker_ = "";
  /**
   * <code>string ticker = 3;</code>
   * @return The ticker.
   */
  @java.lang.Override
  public java.lang.String getTicker() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ticker_ = s;
      return s;
    }
  }
  /**
   * <code>string ticker = 3;</code>
   * @return The bytes for ticker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTickerBytes() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTIDADE_FIELD_NUMBER = 4;
  private long quantidade_ = 0L;
  /**
   * <code>int64 quantidade = 4;</code>
   * @return The quantidade.
   */
  @java.lang.Override
  public long getQuantidade() {
    return quantidade_;
  }

  public static final int PRECOUNITARIO_FIELD_NUMBER = 5;
  private double precoUnitario_ = 0D;
  /**
   * <code>double precoUnitario = 5;</code>
   * @return The precoUnitario.
   */
  @java.lang.Override
  public double getPrecoUnitario() {
    return precoUnitario_;
  }

  public static final int PRECOTOTAL_FIELD_NUMBER = 6;
  private double precoTotal_ = 0D;
  /**
   * <code>double precoTotal = 6;</code>
   * @return The precoTotal.
   */
  @java.lang.Override
  public double getPrecoTotal() {
    return precoTotal_;
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * EXECUTADA, PENDENTE
   * </pre>
   *
   * <code>string status = 7;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * EXECUTADA, PENDENTE
   * </pre>
   *
   * <code>string status = 7;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATACRIACAO_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataCriacao_ = "";
  /**
   * <code>string dataCriacao = 8;</code>
   * @return The dataCriacao.
   */
  @java.lang.Override
  public java.lang.String getDataCriacao() {
    java.lang.Object ref = dataCriacao_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataCriacao_ = s;
      return s;
    }
  }
  /**
   * <code>string dataCriacao = 8;</code>
   * @return The bytes for dataCriacao.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataCriacaoBytes() {
    java.lang.Object ref = dataCriacao_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataCriacao_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ordemId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ordemId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tipo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ticker_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, ticker_);
    }
    if (quantidade_ != 0L) {
      output.writeInt64(4, quantidade_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoUnitario_) != 0) {
      output.writeDouble(5, precoUnitario_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoTotal_) != 0) {
      output.writeDouble(6, precoTotal_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataCriacao_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, dataCriacao_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ordemId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ordemId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tipo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tipo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ticker_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, ticker_);
    }
    if (quantidade_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, quantidade_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoUnitario_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, precoUnitario_);
    }
    if (java.lang.Double.doubleToRawLongBits(precoTotal_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, precoTotal_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataCriacao_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, dataCriacao_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.OrdemInvestimento other = (br.ufc.ds.trabalho2.protobuf.OrdemInvestimento) obj;

    if (!getOrdemId()
        .equals(other.getOrdemId())) return false;
    if (!getTipo()
        .equals(other.getTipo())) return false;
    if (!getTicker()
        .equals(other.getTicker())) return false;
    if (getQuantidade()
        != other.getQuantidade()) return false;
    if (java.lang.Double.doubleToLongBits(getPrecoUnitario())
        != java.lang.Double.doubleToLongBits(
            other.getPrecoUnitario())) return false;
    if (java.lang.Double.doubleToLongBits(getPrecoTotal())
        != java.lang.Double.doubleToLongBits(
            other.getPrecoTotal())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getDataCriacao()
        .equals(other.getDataCriacao())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDEMID_FIELD_NUMBER;
    hash = (53 * hash) + getOrdemId().hashCode();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo().hashCode();
    hash = (37 * hash) + TICKER_FIELD_NUMBER;
    hash = (53 * hash) + getTicker().hashCode();
    hash = (37 * hash) + QUANTIDADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuantidade());
    hash = (37 * hash) + PRECOUNITARIO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrecoUnitario()));
    hash = (37 * hash) + PRECOTOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrecoTotal()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + DATACRIACAO_FIELD_NUMBER;
    hash = (53 * hash) + getDataCriacao().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.OrdemInvestimento prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.OrdemInvestimento}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)
      br.ufc.ds.trabalho2.protobuf.OrdemInvestimentoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.class, br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ordemId_ = "";
      tipo_ = "";
      ticker_ = "";
      quantidade_ = 0L;
      precoUnitario_ = 0D;
      precoTotal_ = 0D;
      status_ = "";
      dataCriacao_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.ModelProto.internal_static_br_ufc_ds_trabalho2_protobuf_OrdemInvestimento_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.OrdemInvestimento getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.OrdemInvestimento build() {
      br.ufc.ds.trabalho2.protobuf.OrdemInvestimento result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.OrdemInvestimento buildPartial() {
      br.ufc.ds.trabalho2.protobuf.OrdemInvestimento result = new br.ufc.ds.trabalho2.protobuf.OrdemInvestimento(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.OrdemInvestimento result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ordemId_ = ordemId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tipo_ = tipo_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ticker_ = ticker_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quantidade_ = quantidade_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.precoUnitario_ = precoUnitario_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.precoTotal_ = precoTotal_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.dataCriacao_ = dataCriacao_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.OrdemInvestimento) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.OrdemInvestimento other) {
      if (other == br.ufc.ds.trabalho2.protobuf.OrdemInvestimento.getDefaultInstance()) return this;
      if (!other.getOrdemId().isEmpty()) {
        ordemId_ = other.ordemId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTipo().isEmpty()) {
        tipo_ = other.tipo_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTicker().isEmpty()) {
        ticker_ = other.ticker_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getQuantidade() != 0L) {
        setQuantidade(other.getQuantidade());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPrecoUnitario()) != 0) {
        setPrecoUnitario(other.getPrecoUnitario());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPrecoTotal()) != 0) {
        setPrecoTotal(other.getPrecoTotal());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getDataCriacao().isEmpty()) {
        dataCriacao_ = other.dataCriacao_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ordemId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tipo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ticker_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              quantidade_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 41: {
              precoUnitario_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              precoTotal_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 58: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              dataCriacao_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ordemId_ = "";
    /**
     * <code>string ordemId = 1;</code>
     * @return The ordemId.
     */
    public java.lang.String getOrdemId() {
      java.lang.Object ref = ordemId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ordemId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ordemId = 1;</code>
     * @return The bytes for ordemId.
     */
    public com.google.protobuf.ByteString
        getOrdemIdBytes() {
      java.lang.Object ref = ordemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ordemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ordemId = 1;</code>
     * @param value The ordemId to set.
     * @return This builder for chaining.
     */
    public Builder setOrdemId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ordemId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ordemId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrdemId() {
      ordemId_ = getDefaultInstance().getOrdemId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ordemId = 1;</code>
     * @param value The bytes for ordemId to set.
     * @return This builder for chaining.
     */
    public Builder setOrdemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ordemId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tipo_ = "";
    /**
     * <pre>
     * COMPRA, VENDA
     * </pre>
     *
     * <code>string tipo = 2;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * COMPRA, VENDA
     * </pre>
     *
     * <code>string tipo = 2;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * COMPRA, VENDA
     * </pre>
     *
     * <code>string tipo = 2;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tipo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * COMPRA, VENDA
     * </pre>
     *
     * <code>string tipo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      tipo_ = getDefaultInstance().getTipo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * COMPRA, VENDA
     * </pre>
     *
     * <code>string tipo = 2;</code>
     * @param value The bytes for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tipo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ticker_ = "";
    /**
     * <code>string ticker = 3;</code>
     * @return The ticker.
     */
    public java.lang.String getTicker() {
      java.lang.Object ref = ticker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ticker = 3;</code>
     * @return The bytes for ticker.
     */
    public com.google.protobuf.ByteString
        getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ticker = 3;</code>
     * @param value The ticker to set.
     * @return This builder for chaining.
     */
    public Builder setTicker(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ticker_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string ticker = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTicker() {
      ticker_ = getDefaultInstance().getTicker();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string ticker = 3;</code>
     * @param value The bytes for ticker to set.
     * @return This builder for chaining.
     */
    public Builder setTickerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ticker_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long quantidade_ ;
    /**
     * <code>int64 quantidade = 4;</code>
     * @return The quantidade.
     */
    @java.lang.Override
    public long getQuantidade() {
      return quantidade_;
    }
    /**
     * <code>int64 quantidade = 4;</code>
     * @param value The quantidade to set.
     * @return This builder for chaining.
     */
    public Builder setQuantidade(long value) {

      quantidade_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 quantidade = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantidade() {
      bitField0_ = (bitField0_ & ~0x00000008);
      quantidade_ = 0L;
      onChanged();
      return this;
    }

    private double precoUnitario_ ;
    /**
     * <code>double precoUnitario = 5;</code>
     * @return The precoUnitario.
     */
    @java.lang.Override
    public double getPrecoUnitario() {
      return precoUnitario_;
    }
    /**
     * <code>double precoUnitario = 5;</code>
     * @param value The precoUnitario to set.
     * @return This builder for chaining.
     */
    public Builder setPrecoUnitario(double value) {

      precoUnitario_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double precoUnitario = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecoUnitario() {
      bitField0_ = (bitField0_ & ~0x00000010);
      precoUnitario_ = 0D;
      onChanged();
      return this;
    }

    private double precoTotal_ ;
    /**
     * <code>double precoTotal = 6;</code>
     * @return The precoTotal.
     */
    @java.lang.Override
    public double getPrecoTotal() {
      return precoTotal_;
    }
    /**
     * <code>double precoTotal = 6;</code>
     * @param value The precoTotal to set.
     * @return This builder for chaining.
     */
    public Builder setPrecoTotal(double value) {

      precoTotal_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double precoTotal = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrecoTotal() {
      bitField0_ = (bitField0_ & ~0x00000020);
      precoTotal_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * EXECUTADA, PENDENTE
     * </pre>
     *
     * <code>string status = 7;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * EXECUTADA, PENDENTE
     * </pre>
     *
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * EXECUTADA, PENDENTE
     * </pre>
     *
     * <code>string status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * EXECUTADA, PENDENTE
     * </pre>
     *
     * <code>string status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * EXECUTADA, PENDENTE
     * </pre>
     *
     * <code>string status = 7;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object dataCriacao_ = "";
    /**
     * <code>string dataCriacao = 8;</code>
     * @return The dataCriacao.
     */
    public java.lang.String getDataCriacao() {
      java.lang.Object ref = dataCriacao_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataCriacao_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataCriacao = 8;</code>
     * @return The bytes for dataCriacao.
     */
    public com.google.protobuf.ByteString
        getDataCriacaoBytes() {
      java.lang.Object ref = dataCriacao_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataCriacao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataCriacao = 8;</code>
     * @param value The dataCriacao to set.
     * @return This builder for chaining.
     */
    public Builder setDataCriacao(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataCriacao_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string dataCriacao = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataCriacao() {
      dataCriacao_ = getDefaultInstance().getDataCriacao();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string dataCriacao = 8;</code>
     * @param value The bytes for dataCriacao to set.
     * @return This builder for chaining.
     */
    public Builder setDataCriacaoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataCriacao_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)
  private static final br.ufc.ds.trabalho2.protobuf.OrdemInvestimento DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.OrdemInvestimento();
  }

  public static br.ufc.ds.trabalho2.protobuf.OrdemInvestimento getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrdemInvestimento>
      PARSER = new com.google.protobuf.AbstractParser<OrdemInvestimento>() {
    @java.lang.Override
    public OrdemInvestimento parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OrdemInvestimento> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrdemInvestimento> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.OrdemInvestimento getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

