// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface OrdemInvestimentoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.OrdemInvestimento)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ordemId = 1;</code>
   * @return The ordemId.
   */
  java.lang.String getOrdemId();
  /**
   * <code>string ordemId = 1;</code>
   * @return The bytes for ordemId.
   */
  com.google.protobuf.ByteString
      getOrdemIdBytes();

  /**
   * <pre>
   * COMPRA, VENDA
   * </pre>
   *
   * <code>string tipo = 2;</code>
   * @return The tipo.
   */
  java.lang.String getTipo();
  /**
   * <pre>
   * COMPRA, VENDA
   * </pre>
   *
   * <code>string tipo = 2;</code>
   * @return The bytes for tipo.
   */
  com.google.protobuf.ByteString
      getTipoBytes();

  /**
   * <code>string ticker = 3;</code>
   * @return The ticker.
   */
  java.lang.String getTicker();
  /**
   * <code>string ticker = 3;</code>
   * @return The bytes for ticker.
   */
  com.google.protobuf.ByteString
      getTickerBytes();

  /**
   * <code>int64 quantidade = 4;</code>
   * @return The quantidade.
   */
  long getQuantidade();

  /**
   * <code>double precoUnitario = 5;</code>
   * @return The precoUnitario.
   */
  double getPrecoUnitario();

  /**
   * <code>double precoTotal = 6;</code>
   * @return The precoTotal.
   */
  double getPrecoTotal();

  /**
   * <pre>
   * EXECUTADA, PENDENTE
   * </pre>
   *
   * <code>string status = 7;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * EXECUTADA, PENDENTE
   * </pre>
   *
   * <code>string status = 7;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string dataCriacao = 8;</code>
   * @return The dataCriacao.
   */
  java.lang.String getDataCriacao();
  /**
   * <code>string dataCriacao = 8;</code>
   * @return The bytes for dataCriacao.
   */
  com.google.protobuf.ByteString
      getDataCriacaoBytes();
}
