// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rmi.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface RemoteObjectRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string objectReference = 1;</code>
   * @return The objectReference.
   */
  java.lang.String getObjectReference();
  /**
   * <code>string objectReference = 1;</code>
   * @return The bytes for objectReference.
   */
  com.google.protobuf.ByteString
      getObjectReferenceBytes();

  /**
   * <code>string hostAddress = 2;</code>
   * @return The hostAddress.
   */
  java.lang.String getHostAddress();
  /**
   * <code>string hostAddress = 2;</code>
   * @return The bytes for hostAddress.
   */
  com.google.protobuf.ByteString
      getHostAddressBytes();

  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>string serviceVersion = 4;</code>
   * @return The serviceVersion.
   */
  java.lang.String getServiceVersion();
  /**
   * <code>string serviceVersion = 4;</code>
   * @return The bytes for serviceVersion.
   */
  com.google.protobuf.ByteString
      getServiceVersionBytes();
}
