// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rmi.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.RemoteObjectRef}
 */
@com.google.protobuf.Generated
public final class RemoteObjectRef extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)
    RemoteObjectRefOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RemoteObjectRef");
  }
  // Use RemoteObjectRef.newBuilder() to construct.
  private RemoteObjectRef(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RemoteObjectRef() {
    objectReference_ = "";
    hostAddress_ = "";
    serviceVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.class, br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.Builder.class);
  }

  public static final int OBJECTREFERENCE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectReference_ = "";
  /**
   * <code>string objectReference = 1;</code>
   * @return The objectReference.
   */
  @java.lang.Override
  public java.lang.String getObjectReference() {
    java.lang.Object ref = objectReference_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectReference_ = s;
      return s;
    }
  }
  /**
   * <code>string objectReference = 1;</code>
   * @return The bytes for objectReference.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectReferenceBytes() {
    java.lang.Object ref = objectReference_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectReference_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTADDRESS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hostAddress_ = "";
  /**
   * <code>string hostAddress = 2;</code>
   * @return The hostAddress.
   */
  @java.lang.Override
  public java.lang.String getHostAddress() {
    java.lang.Object ref = hostAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string hostAddress = 2;</code>
   * @return The bytes for hostAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostAddressBytes() {
    java.lang.Object ref = hostAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 3;
  private int port_ = 0;
  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  @java.lang.Override
  public int getPort() {
    return port_;
  }

  public static final int SERVICEVERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceVersion_ = "";
  /**
   * <code>string serviceVersion = 4;</code>
   * @return The serviceVersion.
   */
  @java.lang.Override
  public java.lang.String getServiceVersion() {
    java.lang.Object ref = serviceVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceVersion = 4;</code>
   * @return The bytes for serviceVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceVersionBytes() {
    java.lang.Object ref = serviceVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectReference_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, objectReference_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hostAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, hostAddress_);
    }
    if (port_ != 0) {
      output.writeInt32(3, port_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, serviceVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectReference_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, objectReference_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hostAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, hostAddress_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, port_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, serviceVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.RemoteObjectRef other = (br.ufc.ds.trabalho2.protobuf.RemoteObjectRef) obj;

    if (!getObjectReference()
        .equals(other.getObjectReference())) return false;
    if (!getHostAddress()
        .equals(other.getHostAddress())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (!getServiceVersion()
        .equals(other.getServiceVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECTREFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getObjectReference().hashCode();
    hash = (37 * hash) + HOSTADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getHostAddress().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + SERVICEVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getServiceVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.RemoteObjectRef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.RemoteObjectRef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)
      br.ufc.ds.trabalho2.protobuf.RemoteObjectRefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.class, br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      objectReference_ = "";
      hostAddress_ = "";
      port_ = 0;
      serviceVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.RemoteObjectRef getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.RemoteObjectRef build() {
      br.ufc.ds.trabalho2.protobuf.RemoteObjectRef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.RemoteObjectRef buildPartial() {
      br.ufc.ds.trabalho2.protobuf.RemoteObjectRef result = new br.ufc.ds.trabalho2.protobuf.RemoteObjectRef(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.RemoteObjectRef result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.objectReference_ = objectReference_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hostAddress_ = hostAddress_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.port_ = port_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.serviceVersion_ = serviceVersion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.RemoteObjectRef) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.RemoteObjectRef other) {
      if (other == br.ufc.ds.trabalho2.protobuf.RemoteObjectRef.getDefaultInstance()) return this;
      if (!other.getObjectReference().isEmpty()) {
        objectReference_ = other.objectReference_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getHostAddress().isEmpty()) {
        hostAddress_ = other.hostAddress_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (!other.getServiceVersion().isEmpty()) {
        serviceVersion_ = other.serviceVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              objectReference_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              hostAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              port_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              serviceVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object objectReference_ = "";
    /**
     * <code>string objectReference = 1;</code>
     * @return The objectReference.
     */
    public java.lang.String getObjectReference() {
      java.lang.Object ref = objectReference_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectReference_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string objectReference = 1;</code>
     * @return The bytes for objectReference.
     */
    public com.google.protobuf.ByteString
        getObjectReferenceBytes() {
      java.lang.Object ref = objectReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string objectReference = 1;</code>
     * @param value The objectReference to set.
     * @return This builder for chaining.
     */
    public Builder setObjectReference(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectReference_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string objectReference = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectReference() {
      objectReference_ = getDefaultInstance().getObjectReference();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string objectReference = 1;</code>
     * @param value The bytes for objectReference to set.
     * @return This builder for chaining.
     */
    public Builder setObjectReferenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectReference_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object hostAddress_ = "";
    /**
     * <code>string hostAddress = 2;</code>
     * @return The hostAddress.
     */
    public java.lang.String getHostAddress() {
      java.lang.Object ref = hostAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostAddress = 2;</code>
     * @return The bytes for hostAddress.
     */
    public com.google.protobuf.ByteString
        getHostAddressBytes() {
      java.lang.Object ref = hostAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostAddress = 2;</code>
     * @param value The hostAddress to set.
     * @return This builder for chaining.
     */
    public Builder setHostAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hostAddress_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string hostAddress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostAddress() {
      hostAddress_ = getDefaultInstance().getHostAddress();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string hostAddress = 2;</code>
     * @param value The bytes for hostAddress to set.
     * @return This builder for chaining.
     */
    public Builder setHostAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hostAddress_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 3;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {

      port_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      bitField0_ = (bitField0_ & ~0x00000004);
      port_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object serviceVersion_ = "";
    /**
     * <code>string serviceVersion = 4;</code>
     * @return The serviceVersion.
     */
    public java.lang.String getServiceVersion() {
      java.lang.Object ref = serviceVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serviceVersion = 4;</code>
     * @return The bytes for serviceVersion.
     */
    public com.google.protobuf.ByteString
        getServiceVersionBytes() {
      java.lang.Object ref = serviceVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceVersion = 4;</code>
     * @param value The serviceVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServiceVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceVersion = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceVersion() {
      serviceVersion_ = getDefaultInstance().getServiceVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string serviceVersion = 4;</code>
     * @param value The bytes for serviceVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServiceVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.RemoteObjectRef)
  private static final br.ufc.ds.trabalho2.protobuf.RemoteObjectRef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.RemoteObjectRef();
  }

  public static br.ufc.ds.trabalho2.protobuf.RemoteObjectRef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoteObjectRef>
      PARSER = new com.google.protobuf.AbstractParser<RemoteObjectRef>() {
    @java.lang.Override
    public RemoteObjectRef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RemoteObjectRef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoteObjectRef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.RemoteObjectRef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

