// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rmi.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public final class RmiProto extends com.google.protobuf.GeneratedFile {
  private RmiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RmiProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_RMIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_RMIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trmi.proto\022\034br.ufc.ds.trabalho2.protobu" +
      "f\"r\n\nRMIRequest\022\023\n\013messageType\030\001 \001(\005\022\021\n\t" +
      "requestId\030\002 \001(\005\022\027\n\017objectReference\030\003 \001(\t" +
      "\022\020\n\010methodId\030\004 \001(\t\022\021\n\targuments\030\005 \001(\014\"f\n" +
      "\010RMIReply\022\023\n\013messageType\030\001 \001(\005\022\021\n\treques" +
      "tId\030\002 \001(\005\022\016\n\006result\030\003 \001(\014\022\021\n\texception\030\004" +
      " \001(\t\022\017\n\007success\030\005 \001(\010\"e\n\017RemoteObjectRef" +
      "\022\027\n\017objectReference\030\001 \001(\t\022\023\n\013hostAddress" +
      "\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\026\n\016serviceVersion\030\004" +
      " \001(\tB*\n\034br.ufc.ds.trabalho2.protobufB\010Rm" +
      "iProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_br_ufc_ds_trabalho2_protobuf_RMIRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_br_ufc_ds_trabalho2_protobuf_RMIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_RMIRequest_descriptor,
        new java.lang.String[] { "MessageType", "RequestId", "ObjectReference", "MethodId", "Arguments", });
    internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor,
        new java.lang.String[] { "MessageType", "RequestId", "Result", "Exception", "Success", });
    internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufc_ds_trabalho2_protobuf_RemoteObjectRef_descriptor,
        new java.lang.String[] { "ObjectReference", "HostAddress", "Port", "ServiceVersion", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
