// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rmi.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

/**
 * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.RMIReply}
 */
@com.google.protobuf.Generated
public final class RMIReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:br.ufc.ds.trabalho2.protobuf.RMIReply)
    RMIReplyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RMIReply");
  }
  // Use RMIReply.newBuilder() to construct.
  private RMIReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RMIReply() {
    result_ = com.google.protobuf.ByteString.EMPTY;
    exception_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufc.ds.trabalho2.protobuf.RMIReply.class, br.ufc.ds.trabalho2.protobuf.RMIReply.Builder.class);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private int messageType_ = 0;
  /**
   * <pre>
   * 1 = Reply
   * </pre>
   *
   * <code>int32 messageType = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public int getMessageType() {
    return messageType_;
  }

  public static final int REQUESTID_FIELD_NUMBER = 2;
  private int requestId_ = 0;
  /**
   * <code>int32 requestId = 2;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public int getRequestId() {
    return requestId_;
  }

  public static final int RESULT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes result = 3;</code>
   * @return The result.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getResult() {
    return result_;
  }

  public static final int EXCEPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object exception_ = "";
  /**
   * <code>string exception = 4;</code>
   * @return The exception.
   */
  @java.lang.Override
  public java.lang.String getException() {
    java.lang.Object ref = exception_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exception_ = s;
      return s;
    }
  }
  /**
   * <code>string exception = 4;</code>
   * @return The bytes for exception.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExceptionBytes() {
    java.lang.Object ref = exception_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exception_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESS_FIELD_NUMBER = 5;
  private boolean success_ = false;
  /**
   * <code>bool success = 5;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != 0) {
      output.writeInt32(1, messageType_);
    }
    if (requestId_ != 0) {
      output.writeInt32(2, requestId_);
    }
    if (!result_.isEmpty()) {
      output.writeBytes(3, result_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(exception_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, exception_);
    }
    if (success_ != false) {
      output.writeBool(5, success_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, messageType_);
    }
    if (requestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, requestId_);
    }
    if (!result_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, result_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(exception_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, exception_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, success_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufc.ds.trabalho2.protobuf.RMIReply)) {
      return super.equals(obj);
    }
    br.ufc.ds.trabalho2.protobuf.RMIReply other = (br.ufc.ds.trabalho2.protobuf.RMIReply) obj;

    if (getMessageType()
        != other.getMessageType()) return false;
    if (getRequestId()
        != other.getRequestId()) return false;
    if (!getResult()
        .equals(other.getResult())) return false;
    if (!getException()
        .equals(other.getException())) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
    hash = (53 * hash) + getException().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufc.ds.trabalho2.protobuf.RMIReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufc.ds.trabalho2.protobuf.RMIReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code br.ufc.ds.trabalho2.protobuf.RMIReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:br.ufc.ds.trabalho2.protobuf.RMIReply)
      br.ufc.ds.trabalho2.protobuf.RMIReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.ds.trabalho2.protobuf.RMIReply.class, br.ufc.ds.trabalho2.protobuf.RMIReply.Builder.class);
    }

    // Construct using br.ufc.ds.trabalho2.protobuf.RMIReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageType_ = 0;
      requestId_ = 0;
      result_ = com.google.protobuf.ByteString.EMPTY;
      exception_ = "";
      success_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufc.ds.trabalho2.protobuf.RmiProto.internal_static_br_ufc_ds_trabalho2_protobuf_RMIReply_descriptor;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.RMIReply getDefaultInstanceForType() {
      return br.ufc.ds.trabalho2.protobuf.RMIReply.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.RMIReply build() {
      br.ufc.ds.trabalho2.protobuf.RMIReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufc.ds.trabalho2.protobuf.RMIReply buildPartial() {
      br.ufc.ds.trabalho2.protobuf.RMIReply result = new br.ufc.ds.trabalho2.protobuf.RMIReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.ufc.ds.trabalho2.protobuf.RMIReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageType_ = messageType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.result_ = result_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.exception_ = exception_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufc.ds.trabalho2.protobuf.RMIReply) {
        return mergeFrom((br.ufc.ds.trabalho2.protobuf.RMIReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufc.ds.trabalho2.protobuf.RMIReply other) {
      if (other == br.ufc.ds.trabalho2.protobuf.RMIReply.getDefaultInstance()) return this;
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      if (other.getRequestId() != 0) {
        setRequestId(other.getRequestId());
      }
      if (!other.getResult().isEmpty()) {
        setResult(other.getResult());
      }
      if (!other.getException().isEmpty()) {
        exception_ = other.exception_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageType_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              requestId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              result_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              exception_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              success_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int messageType_ ;
    /**
     * <pre>
     * 1 = Reply
     * </pre>
     *
     * <code>int32 messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <pre>
     * 1 = Reply
     * </pre>
     *
     * <code>int32 messageType = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(int value) {

      messageType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1 = Reply
     * </pre>
     *
     * <code>int32 messageType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = 0;
      onChanged();
      return this;
    }

    private int requestId_ ;
    /**
     * <code>int32 requestId = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>int32 requestId = 2;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(int value) {

      requestId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 requestId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes result = 3;</code>
     * @return The result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResult() {
      return result_;
    }
    /**
     * <code>bytes result = 3;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      result_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes result = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      bitField0_ = (bitField0_ & ~0x00000004);
      result_ = getDefaultInstance().getResult();
      onChanged();
      return this;
    }

    private java.lang.Object exception_ = "";
    /**
     * <code>string exception = 4;</code>
     * @return The exception.
     */
    public java.lang.String getException() {
      java.lang.Object ref = exception_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exception_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exception = 4;</code>
     * @return The bytes for exception.
     */
    public com.google.protobuf.ByteString
        getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exception = 4;</code>
     * @param value The exception to set.
     * @return This builder for chaining.
     */
    public Builder setException(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      exception_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string exception = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearException() {
      exception_ = getDefaultInstance().getException();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string exception = 4;</code>
     * @param value The bytes for exception to set.
     * @return This builder for chaining.
     */
    public Builder setExceptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      exception_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 5;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 5;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000010);
      success_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:br.ufc.ds.trabalho2.protobuf.RMIReply)
  }

  // @@protoc_insertion_point(class_scope:br.ufc.ds.trabalho2.protobuf.RMIReply)
  private static final br.ufc.ds.trabalho2.protobuf.RMIReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufc.ds.trabalho2.protobuf.RMIReply();
  }

  public static br.ufc.ds.trabalho2.protobuf.RMIReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RMIReply>
      PARSER = new com.google.protobuf.AbstractParser<RMIReply>() {
    @java.lang.Override
    public RMIReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RMIReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RMIReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufc.ds.trabalho2.protobuf.RMIReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

