// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rmi.proto
// Protobuf Java Version: 4.34.1

package br.ufc.ds.trabalho2.protobuf;

@com.google.protobuf.Generated
public interface RMIReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufc.ds.trabalho2.protobuf.RMIReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1 = Reply
   * </pre>
   *
   * <code>int32 messageType = 1;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>int32 requestId = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>bytes result = 3;</code>
   * @return The result.
   */
  com.google.protobuf.ByteString getResult();

  /**
   * <code>string exception = 4;</code>
   * @return The exception.
   */
  java.lang.String getException();
  /**
   * <code>string exception = 4;</code>
   * @return The bytes for exception.
   */
  com.google.protobuf.ByteString
      getExceptionBytes();

  /**
   * <code>bool success = 5;</code>
   * @return The success.
   */
  boolean getSuccess();
}
